### ISSUE TITLE
NUM_CORE_BARCODES influences the output of DigitalExpression

### ISSUE THREAD

**Issue by jwdy** [broadinstitute/Drop-seq#104]
Hi,
    When I used DigitalExpression of Drop-seq tools 2.1.0, I tried to set NUM_CORE_BARCODES to different values. Then something strange happened in the out_gene_exon_tagged.dge.summary.txt. 
    For example, when I set NUM_CORE_BARCODES=8000, NUM_TRANSCRIPTS equaled to 0 starting form line 7950. Unexpectedly, the situation that NUM_TRANSCRIPTS equaled to 0 also happened when I set NUM_CORE_BARCODES to a number less than 7950, like 5000. 
    Shouldn't the first x lines be the same when NUM_CORE_BARCODES is different? Is there something wrong? 
    Thanks!
    Jiawei

**Comment by jamesnemesh** [comment]
Are you setting both NUM_TRANSCRIPTS and NUM_CORE_BARCODES?

When you set NUM_CORE_BARCODES, the output is ordered by the number of reads per cell barcode.

-Jim

**Comment by jwdy** [comment]
I only use NUM_CORE_BARCODES because NUM_CORE_BARCODES is finally bugfixed and working in V2.0.0.

Jiawei

**Comment by jwdy** [comment]
I only use NUM_CORE_BARCODES because MIN_NUM_TRANSCRIPTS_PER_CELL​​ seems to not work in V2.1.0.

Jiawei

**Comment by jwdy** [comment]
And in my out_gene_exon_tagged.dge.summary.txt, the output is ordered by the NUM_TRANSCRIPTS.
