### ISSUE TITLE
TagBamWithReadSequenceExtended  | Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/dropseqrna/cmdline/DropSeqMain : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by jolespin** [broadinstitute/Drop-seq#116]
### Instructions

TagBamWithReadSequenceExtended  | Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/dropseqrna/cmdline/DropSeqMain : Unsupported major.minor version 52.0

### Affected tool(s)
TagBamWithReadSequenceExtended

### Affected version(s)
Drop-seq_tools-2.1.0

### Description 
I'm getting an error when running `TagBamWithReadSequenceExtended` early in the pipeline.  `unaligned_data.bam` is `3.4G`

#### Steps to reproduce
```
## Tagging bam with read sequence [Cell]
/home/jespinoz/Algorithms/Pipelines/dropseq_pipeline/Drop-seq_tools-2.1.0/TagBamWithReadSequenceExtended INPUT=dropseq_output_data1/Undetermined_S0/unaligned_data.bam OUTPUT=dropseq_output_data1/Undetermined_S0/unaligned_tagged_Cell.bam SUMMARY=dropseq_output_data1/Undetermined_S0/unaligned_tagged_Cell.bam_summary.txt BASE_RANGE=1-12 BASE_QUALITY=10 BARCODED_READ=1 DISCARD_READ=False TAG_NAME=XC NUM_BASES_BELOW_QUALITY=1 &> dropseq_output_data1/Undetermined_S0/logging/unaligned_tagged_Cell.bam.log
```

#### Expected behavior
To produce the file without error

#### Actual behavior
```
cat dropseq_output_data1/Undetermined_S0/logging/unaligned_tagged_Cell.bam.log

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/broadinstitute/dropseqrna/cmdline/DropSeqMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

#### Output of previous step to create `unaligned_data.bam`
<details><summary>FastqToSam</summary>
<p>

(dropseq_env) -bash-4.1$ cat dropseq_output_data1/Undetermined_S0/logging/unaligned_data.bam.log
INFO	2019-03-28 16:57:04	FastqToSam

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    FastqToSam -F1 /usr/local/projdata/0568/projects/PLANKTON/illumina_aallen/jespinoz/Fastq/data1/Undetermined_S0_R1.fastq.gz -F2 /usr/local/projdata/0568/projects/PLANKTON/illumina_aallen/jespinoz/Fastq/data1/Undetermined_S0_R2.fastq.gz -O dropseq_output_data1/Undetermined_S0/unaligned_data.bam -SM Undetermined_S0 -TMP_DIR dropseq_output_data1/Undetermined_S0/tmp
**********

16:57:06.429 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/jespinoz/Algorithms/Pipelines/dropseq_pipeline/Drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Mar 28 16:57:06 EDT 2019] FastqToSam FASTQ=/usr/local/projdata/0568/projects/PLANKTON/illumina_aallen/jespinoz/Fastq/data1/Undetermined_S0_R1.fastq.gz FASTQ2=/usr/local/projdata/0568/projects/PLANKTON/illumina_aallen/jespinoz/Fastq/data1/Undetermined_S0_R2.fastq.gz OUTPUT=dropseq_output_data1/Undetermined_S0/unaligned_data.bam SAMPLE_NAME=Undetermined_S0 TMP_DIR=[dropseq_output_data1/Undetermined_S0/tmp]    USE_SEQUENTIAL_FASTQS=false READ_GROUP_NAME=A SORT_ORDER=queryname MIN_Q=0 MAX_Q=93 STRIP_UNPAIRED_MATE_NUMBER=false ALLOW_AND_IGNORE_EMPTY_LINES=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 28 16:57:06 EDT 2019] Executing as jespinoz@dell-2.jcvi.org on Linux 2.6.32-696.18.7.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_121-b13; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.18.14-SNAPSHOT
INFO	2019-03-28 16:57:06	FastqToSam	Auto-detected quality format as: Standard.
INFO	2019-03-28 16:57:10	FastqToSam	Processed     1,000,000 records.  Elapsed time: 00:00:03s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:13	FastqToSam	Processed     2,000,000 records.  Elapsed time: 00:00:06s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:16	FastqToSam	Processed     3,000,000 records.  Elapsed time: 00:00:09s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:19	FastqToSam	Processed     4,000,000 records.  Elapsed time: 00:00:12s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:22	FastqToSam	Processed     5,000,000 records.  Elapsed time: 00:00:15s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:25	FastqToSam	Processed     6,000,000 records.  Elapsed time: 00:00:18s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:28	FastqToSam	Processed     7,000,000 records.  Elapsed time: 00:00:21s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:31	FastqToSam	Processed     8,000,000 records.  Elapsed time: 00:00:24s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:34	FastqToSam	Processed     9,000,000 records.  Elapsed time: 00:00:27s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:37	FastqToSam	Processed    10,000,000 records.  Elapsed time: 00:00:30s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:40	FastqToSam	Processed    11,000,000 records.  Elapsed time: 00:00:33s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:42	FastqToSam	Processed    12,000,000 records.  Elapsed time: 00:00:36s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:46	FastqToSam	Processed    13,000,000 records.  Elapsed time: 00:00:39s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:49	FastqToSam	Processed    14,000,000 records.  Elapsed time: 00:00:42s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:52	FastqToSam	Processed    15,000,000 records.  Elapsed time: 00:00:45s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:57:55	FastqToSam	Processed    16,000,000 records.  Elapsed time: 00:00:48s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:57:58	FastqToSam	Processed    17,000,000 records.  Elapsed time: 00:00:51s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:01	FastqToSam	Processed    18,000,000 records.  Elapsed time: 00:00:54s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:58:04	FastqToSam	Processed    19,000,000 records.  Elapsed time: 00:00:57s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:58:07	FastqToSam	Processed    20,000,000 records.  Elapsed time: 00:01:00s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:58:10	FastqToSam	Processed    21,000,000 records.  Elapsed time: 00:01:03s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:13	FastqToSam	Processed    22,000,000 records.  Elapsed time: 00:01:06s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:16	FastqToSam	Processed    23,000,000 records.  Elapsed time: 00:01:09s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:19	FastqToSam	Processed    24,000,000 records.  Elapsed time: 00:01:12s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:22	FastqToSam	Processed    25,000,000 records.  Elapsed time: 00:01:15s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:24	FastqToSam	Processed    26,000,000 records.  Elapsed time: 00:01:18s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:27	FastqToSam	Processed    27,000,000 records.  Elapsed time: 00:01:20s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:30	FastqToSam	Processed    28,000,000 records.  Elapsed time: 00:01:23s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:33	FastqToSam	Processed    29,000,000 records.  Elapsed time: 00:01:26s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:36	FastqToSam	Processed    30,000,000 records.  Elapsed time: 00:01:29s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:39	FastqToSam	Processed    31,000,000 records.  Elapsed time: 00:01:32s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:42	FastqToSam	Processed    32,000,000 records.  Elapsed time: 00:01:35s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:44	FastqToSam	Processed    33,000,000 records.  Elapsed time: 00:01:38s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:47	FastqToSam	Processed    34,000,000 records.  Elapsed time: 00:01:40s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:50	FastqToSam	Processed    35,000,000 records.  Elapsed time: 00:01:43s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:58:55	FastqToSam	Processed    36,000,000 records.  Elapsed time: 00:01:48s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO	2019-03-28 16:58:58	FastqToSam	Processed    37,000,000 records.  Elapsed time: 00:01:51s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:00	FastqToSam	Processed    38,000,000 records.  Elapsed time: 00:01:54s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:03	FastqToSam	Processed    39,000,000 records.  Elapsed time: 00:01:56s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:06	FastqToSam	Processed    40,000,000 records.  Elapsed time: 00:01:59s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:09	FastqToSam	Processed    41,000,000 records.  Elapsed time: 00:02:02s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:12	FastqToSam	Processed    42,000,000 records.  Elapsed time: 00:02:05s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:15	FastqToSam	Processed    43,000,000 records.  Elapsed time: 00:02:08s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:17	FastqToSam	Processed    44,000,000 records.  Elapsed time: 00:02:11s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:20	FastqToSam	Processed    45,000,000 records.  Elapsed time: 00:02:13s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:23	FastqToSam	Processed    46,000,000 records.  Elapsed time: 00:02:16s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:26	FastqToSam	Processed    47,000,000 records.  Elapsed time: 00:02:19s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:29	FastqToSam	Processed    48,000,000 records.  Elapsed time: 00:02:22s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:32	FastqToSam	Processed    49,000,000 records.  Elapsed time: 00:02:25s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:34	FastqToSam	Processed    50,000,000 records.  Elapsed time: 00:02:28s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:37	FastqToSam	Processed    51,000,000 records.  Elapsed time: 00:02:30s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:40	FastqToSam	Processed    52,000,000 records.  Elapsed time: 00:02:33s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:43	FastqToSam	Processed    53,000,000 records.  Elapsed time: 00:02:36s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:46	FastqToSam	Processed    54,000,000 records.  Elapsed time: 00:02:39s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 16:59:49	FastqToSam	Processed    55,000,000 records.  Elapsed time: 00:02:42s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:52	FastqToSam	Processed    56,000,000 records.  Elapsed time: 00:02:45s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:55	FastqToSam	Processed    57,000,000 records.  Elapsed time: 00:02:48s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 16:59:57	FastqToSam	Processed    58,000,000 records.  Elapsed time: 00:02:51s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:00	FastqToSam	Processed    59,000,000 records.  Elapsed time: 00:02:53s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:03	FastqToSam	Processed    60,000,000 records.  Elapsed time: 00:02:56s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:06	FastqToSam	Processed    61,000,000 records.  Elapsed time: 00:02:59s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:09	FastqToSam	Processed    62,000,000 records.  Elapsed time: 00:03:02s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 17:00:12	FastqToSam	Processed    63,000,000 records.  Elapsed time: 00:03:05s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:15	FastqToSam	Processed    64,000,000 records.  Elapsed time: 00:03:08s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:18	FastqToSam	Processed    65,000,000 records.  Elapsed time: 00:03:11s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:21	FastqToSam	Processed    66,000,000 records.  Elapsed time: 00:03:14s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:24	FastqToSam	Processed    67,000,000 records.  Elapsed time: 00:03:17s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:26	FastqToSam	Processed    68,000,000 records.  Elapsed time: 00:03:20s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:29	FastqToSam	Processed    69,000,000 records.  Elapsed time: 00:03:23s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:32	FastqToSam	Processed    70,000,000 records.  Elapsed time: 00:03:25s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:36	FastqToSam	Processed    71,000,000 records.  Elapsed time: 00:03:29s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 17:00:39	FastqToSam	Processed    72,000,000 records.  Elapsed time: 00:03:32s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:42	FastqToSam	Processed    73,000,000 records.  Elapsed time: 00:03:35s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:45	FastqToSam	Processed    74,000,000 records.  Elapsed time: 00:03:38s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:47	FastqToSam	Processed    75,000,000 records.  Elapsed time: 00:03:41s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:50	FastqToSam	Processed    76,000,000 records.  Elapsed time: 00:03:44s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:53	FastqToSam	Processed    77,000,000 records.  Elapsed time: 00:03:46s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:56	FastqToSam	Processed    78,000,000 records.  Elapsed time: 00:03:49s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:00:59	FastqToSam	Processed    79,000,000 records.  Elapsed time: 00:03:52s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:02	FastqToSam	Processed    80,000,000 records.  Elapsed time: 00:03:55s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:05	FastqToSam	Processed    81,000,000 records.  Elapsed time: 00:03:58s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:07	FastqToSam	Processed    82,000,000 records.  Elapsed time: 00:04:01s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:10	FastqToSam	Processed    83,000,000 records.  Elapsed time: 00:04:04s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:13	FastqToSam	Processed    84,000,000 records.  Elapsed time: 00:04:06s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:16	FastqToSam	Processed    85,000,000 records.  Elapsed time: 00:04:09s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:19	FastqToSam	Processed    86,000,000 records.  Elapsed time: 00:04:12s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:22	FastqToSam	Processed    87,000,000 records.  Elapsed time: 00:04:15s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:26	FastqToSam	Processed    88,000,000 records.  Elapsed time: 00:04:19s.  Time for last 1,000,000:    4s.  Last read position: */*
INFO	2019-03-28 17:01:29	FastqToSam	Processed    89,000,000 records.  Elapsed time: 00:04:22s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:32	FastqToSam	Processed    90,000,000 records.  Elapsed time: 00:04:25s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:38	FastqToSam	Processed    91,000,000 records.  Elapsed time: 00:04:31s.  Time for last 1,000,000:    6s.  Last read position: */*
INFO	2019-03-28 17:01:41	FastqToSam	Processed    92,000,000 records.  Elapsed time: 00:04:34s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:44	FastqToSam	Processed    93,000,000 records.  Elapsed time: 00:04:37s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:47	FastqToSam	Processed    94,000,000 records.  Elapsed time: 00:04:40s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:49	FastqToSam	Processed    95,000,000 records.  Elapsed time: 00:04:43s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:52	FastqToSam	Processed    96,000,000 records.  Elapsed time: 00:04:46s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:55	FastqToSam	Processed    97,000,000 records.  Elapsed time: 00:04:48s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:01:58	FastqToSam	Processed    98,000,000 records.  Elapsed time: 00:04:51s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:01	FastqToSam	Processed    99,000,000 records.  Elapsed time: 00:04:54s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:04	FastqToSam	Processed   100,000,000 records.  Elapsed time: 00:04:57s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:07	FastqToSam	Processed   101,000,000 records.  Elapsed time: 00:05:00s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:09	FastqToSam	Processed   102,000,000 records.  Elapsed time: 00:05:03s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:12	FastqToSam	Processed   103,000,000 records.  Elapsed time: 00:05:06s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:15	FastqToSam	Processed   104,000,000 records.  Elapsed time: 00:05:08s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:18	FastqToSam	Processed   105,000,000 records.  Elapsed time: 00:05:11s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:21	FastqToSam	Processed   106,000,000 records.  Elapsed time: 00:05:15s.  Time for last 1,000,000:    3s.  Last read position: */*
INFO	2019-03-28 17:02:24	FastqToSam	Processed   107,000,000 records.  Elapsed time: 00:05:17s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:27	FastqToSam	Processed   108,000,000 records.  Elapsed time: 00:05:20s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:30	FastqToSam	Processed   109,000,000 records.  Elapsed time: 00:05:23s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:33	FastqToSam	Processed   110,000,000 records.  Elapsed time: 00:05:26s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:35	FastqToSam	Processed   111,000,000 records.  Elapsed time: 00:05:29s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:38	FastqToSam	Processed   112,000,000 records.  Elapsed time: 00:05:32s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:41	FastqToSam	Processed   113,000,000 records.  Elapsed time: 00:05:34s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:44	FastqToSam	Processed   114,000,000 records.  Elapsed time: 00:05:37s.  Time for last 1,000,000:    2s.  Last read position: */*
INFO	2019-03-28 17:02:47	FastqToSam	Processed 57413960 fastq reads
INFO	2019-03-28 17:02:48	SortingCollection	Creating merging iterator from 230 files
[Thu Mar 28 17:09:29 EDT 2019] picard.sam.FastqToSam done. Elapsed time: 12.38 minutes.

</p>
</details>

**Comment by alecw** [comment]
Hi @jolespin ,

Your version of Java is too old.  You need to use 1.8.

-Alec

**Comment by jolespin** [comment]
I double checked the script I'm running and it's using that version of java:
```
(dropseq_env) -bash-4.1$ /usr/local/packages/jdk-8u121/bin/java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
(dropseq_env) -bash-4.1$ /usr/local/packages/jdk-8u121/bin/java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by alecw** [comment]
Hi @jolespin ,

Run `java -version` without path, so you can see what version is on your path.  My guess is that your path is not pointing at /usr/local/packages/jdk-8u121/bin/java

-Alec

**Comment by jolespin** [comment]
Thanks @alecw ! It's calling `/usr/local/bin/java`.  Is there a way to explicitly call the program with `/usr/local/packages/jdk-8u121/bin/java`? I'm not very familiar with java.  I set an alias in my `.bash_profile` but when I run jobs on the grid it doesn't keep the alias even with the `-V` via `qsub`.

**Comment by jolespin** [comment]
I just brought `/usr/local/packages/jdk-8u121/bin/` to the front of my path and I'm rerunning.  I'll post the results once I get them.  Thanks again.

**Comment by jolespin** [comment]
The run just finished now.  It was definitely the java version.  Thank you for catching that!  Quick question, is there a repository with example dropseq reads that I could run to test my pipeline?
