### ISSUE TITLE
How are `NUM_GENIC_READS`, `NUM_TRANSCRIPTS`, and `NUM_GENES` defined in DigitalExpression?

### ISSUE THREAD

**Issue by jolespin** [broadinstitute/Drop-seq#122]
### Instructions

How are `NUM_GENIC_READS`, `NUM_TRANSCRIPTS`, and `NUM_GENES` defined?  It appears that `NUM_GENIC_READS` should be the total number of reads that mapped to genes while `NUM_TRANSCRIPTS` is the number of total transcripts detected (as for genes).  However, I'm not seeing this when I look at the raw data output. 

### Here's my command:
```
DigitalExpression SUMMARY=dropseq_output/Fresh_HJGKNBGX5/out_gene_exon_tagged.dge.txt.gz.expression.summary.txt OUTPUT=dropseq_output/Fresh_HJGKNBGX5/out_gene_exon_tagged.dge.txt.gz INPUT=dropseq_output/Fresh_HJGKNBGX5/cleaned_substitution-synthesis.bam NUM_CORE_BARCODES=10000 GENE_NAME_TAG=gn    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf STRAND_STRATEGY=SENSE LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
```

#### Here's the output of `out_gene_exon_tagged.dge.txt.gz.expression.summary.txt `
```
CELL_BARCODE	NUM_GENIC_READS	NUM_TRANSCRIPTS	NUM_GENES
TAAGCAGTGGTA	838	596	595
TATGACCCTGGT	7518	542	446
CCTTCCCGTAAG	8718	469	379
CGTAAATTCCTA	8014	436	306
AAGTCAAGGGTA	5201	420	348
TTCTCGGGCTTC	3878	382	288
CTTCCAGGATAC	5693	368	310
AGTCGCAACTAA	6882	356	309
```
#### Here's when I load in the table and sort by the total number of counts per barcode:

![image](https://user-images.githubusercontent.com/9061708/56316241-a5c37f80-610e-11e9-805c-37a8ed7cf730.png)
These values correspond with the `NUM_TRANSCRIPTS` column

#### Here's I count the number of unique transcripts per barcode:  
![image](https://user-images.githubusercontent.com/9061708/56316485-41ed8680-610f-11e9-906f-285c045d777d.png)
These values correspond with the `NUM_GENES` column

**How can I interpret the `NUM_GENIC_READS` column?**

**Comment by jamesnemesh** [comment]
The NUM_GENIC_READS is the number of reads that we encounter on a cell, given the accepted locus function/strand rules applied.

Back when we just supported coding, those were the exonic reads - ie: any read that was tagged with a GE:Z tag on a cell barcode and the read was on the correct strand, and the read was not ambiguously assigned to multiple genes.

What is the “number of counts per barcode”?  Counts of reads (but not the carefully curated list of reads that passed all filters for analysis, but all reads?). You’d expect correlation in most cells for these metrics (there are some strange cells that are dominated by the number of intronic reads in an experiment that doesn’t contain nuclei, for example), but they wouldn’t be equal.

-Jim

**Comment by jolespin** [comment]
Thanks for getting back to me so quickly!  I'm trying to follow your last response and I'm wondering if I understand correctly.  
(1) The `NUM_GENIC_READS` is the  “number of counts per barcode” and this IS NOT determined from the `out_gene_exon_tagged.dge.txt.gz` counts table? 
(2) If I've chosen `LOCUS_FUNCTION_LIST=[CODING, UTR]` does that mean the extra reads from the `NUM_GENIC_READS` column could be intronic? 
(3) I'm still struggling to understand why the total reads summed up for a particular cell barcode (e.g. `TATGACCCTGGT` is `542` total counts) is not the same as the `NUM_GENIC_READS` column (e.g. `TATGACCCTGGT`'s `NUM_GENIC_READS = 7518` )

**Comment by jamesnemesh** [comment]
The file out_gene_exon_tagged.dge.txt.gz is a matrix of the count of TRANSCRIPTS per cell/gene (not reads!).  The number of reads will always be >= number of transcripts, but by how different amounts depending on a huge number of factors.

Let’s take a really simple example:

You have one cell with a total of 10 transcripts that you capture.  You sequence it to the amazing depth of 5 total reads.  The BEST you can do is capture a unique transcript with each read, so the number of transcripts will be at most 5.  Encouraged by your success, you now sequence 10,000 reads.  If each transcript is equally likely to be seen, you’ll distribute your reads across all of your UMIs equally, and each UMI gets 1000 reads.  No matter how many reads you sequence, you’ll never get more than 10 total transcripts.

You should try running GatherMolecularBarcodeDistributionByGene instead.  In that case, the output is the cell barcode, the gene, the UMI sequence, and the number of reads.  Then you can see how reads are distributed across a cell, and across genes and UMIs, and how it’s rather uneven.

-Jim

**Comment by jolespin** [comment]
> The file out_gene_exon_tagged.dge.txt.gz is a matrix of the count of TRANSCRIPTS per cell/gene (not reads!).  The number of reads will always be >= number of transcripts, but by how different amounts depending on a huge number of factors.
This must be where my logic was flawed.  My interpretation of the counts table was the following: In the counts matrix `M`, for each cell-barcode `i`, and each transcript identifier `j` there would be the number of counts (the number of reads mapped) for the pair (i.e. `gene_j` of `cellbarcode_i`) at each `M[i,j]`.  Is this logic incorrect? If so, are the counts of "TRANSCRIPTS per cell/gene" an estimate on the physical pieces of RNA that were detected? 


> Let’s take a really simple example:
> 
> You have one cell with a total of 10 transcripts that you capture.  You sequence it to the amazing depth of 5 total reads.  The BEST you can do is capture a unique transcript with each read, so the number of transcripts will be at most 5.  Encouraged by your success, you now sequence 10,000 reads.  If each transcript is equally likely to be seen, you’ll distribute your reads across all of your UMIs equally, and each UMI gets 1000 reads.  No matter how many reads you sequence, you’ll never get more than 10 total transcripts.

This makes perfect sense.  The number of unique transcripts detected can never be more than the number reads available.  There are only 10 transcripts in the GTF file so one can only have 10 transcripts total in the output matrix. Is the `UMI` a unique variant of the transcript sequence in the GTF file or are `UMI` and transcript synonymous in this setting?


> You should try running GatherMolecularBarcodeDistributionByGene instead.  In that case, the output is the cell barcode, the gene, the UMI sequence, and the number of reads.  Then you can see how reads are distributed across a cell, and across genes and UMIs, and how it’s rather uneven.

If I created a matrix from the output of `GatherMolecularBarcodeDistributionByGene` and group by `cell barcode` and `gene` would I get the same output as the `DigitalExpression` output (provided the parameters were the same)?  If not, would this be the (potentially flawed logic) "counts" table I referred to above?

**Comment by jamesnemesh** [comment]
GatherMolecularBarcodeDistributionByGene and DigitalExpression use the same underlying code, and output the same results.  The former just provides a more verbose output, but the number of UMIs/reads/genes should match on both.

-Jim

**Comment by jolespin** [comment]
`GatherMolecularBarcodeDistributionByGene` is exactly what I was looking for!   Now I understand what each of these fields are referring to in the output summary.  Thank you. 

I processed the data like this in Python to make sense of what was happening: 
```python
# Read in output from GatherMolecularBarcodeDistributionByGene
df_barcode_distribution = pd.read_csv("molecular_barcode_distribution.tsv.gz", sep="\t", compression="gzip")

# Create the structure for a dataframe
d_reads = defaultdict(lambda: defaultdict(int))
d_molecular_barcodes = defaultdict(lambda: defaultdict(int))

# For each cellbarcode add the num observations or the unique molecular barcode
for id_cellbarcode, data in df_barcode_distribution.iterrows():
    d_reads[id_cellbarcode][data["Gene"]] += data["Num_Obs"]
    d_molecular_barcodes[id_cellbarcode][data["Gene"]] += 1

# Convert these into counts tables
df_reads = pd.DataFrame(d_reads).T.fillna(0).astype(int)
df_molbarcodes = pd.DataFrame(d_molecular_barcodes).T.fillna(0).astype(int)

idx_query_cellbarcodes = ["TAAGCAGTGGTA", "TATGACCCTGGT", "CCTTCCCGTAAG", "CGTAAATTCCTA", "AAGTCAAGGGTA", "TTCTCGGGCTTC", "CTTCCAGGATAC", "AGTCGCAACTAA"]

# DigitalExpression summary
pd.concat([
    # Column 1
    df_reads.loc[idx_query_cellbarcodes,:].sum(axis=1).to_frame("NUM_GENIC_READS"),
    # Column 2
    df_molbarcodes.loc[idx_query_cellbarcodes,:].sum(axis=1).to_frame("NUM_TRANSCRIPTS"),
    # Column 3
    (df_reads.loc[idx_query_cellbarcodes,:] > 0).sum(axis=1).to_frame("NUM_GENES"),
], axis=1)

```
![image](https://user-images.githubusercontent.com/9061708/56445089-561cb980-62b0-11e9-98a2-e037b342b3fa.png)

![image](https://user-images.githubusercontent.com/9061708/56445098-603eb800-62b0-11e9-9075-536f09056c0c.png)
