### ISSUE TITLE
How to draw Fig 3A in your 2015 Cell paper?

### ISSUE THREAD

**Issue by DawnEve** [broadinstitute/Drop-seq#124]
### Instructions

- I have tried to draw a figure similar to Fig 3A in your 2015 Cell paper, but information are not intact.

### Tool(s) involved
STAR

### Description 
I have a c1 data from a mixture sample of human and mouse cells. I use STAR to map against mm10 and hg19, but unique counts plot doesnot look that clear. 

I want to know how you solved this problem.

Thank you.

**Comment by alecw** [comment]
Hi DawnEve,

It would be helpful to know what your plot looks like, and how you generated it.

-Alec

**Comment by DawnEve** [comment]
1.I mapped each cell to hg19 and mm10 using STAR_2.5.2b.

2.Then ploting each cell using uniquely mapped ratio on mouse and human as x and y axis respectively.
I draw the second picture using uniquely mapped counts.

3.My picture
![hg19_mm10](https://user-images.githubusercontent.com/5974903/57685502-9a5e6800-766a-11e9-9486-8a994c1676d3.png)

**Comment by jamesnemesh** [comment]
Please look at the dropseq cookbook, at the last section titled “Mixed-species plots”.

The first most obvious thing wrong is that you’re plotting counts of reads, not UMIs.

-Jim

**Comment by DawnEve** [comment]
As far as I know, C1 mRNA Seq HT IFC doesnot have the so called UMI

**Comment by jamesnemesh** [comment]
That’s true, C1 does not have UMIs. However, the data from figure 3 isn’t from C1 data, but dropseq data:
Figure 3. Critical Evaluation of Drop-Seq Using Species-Mixing Experiments

(A and B) Drop-seq analysis of mixutres of mouse <https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/mouse> and human <https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/human> cells <https://www.sciencedirect.com/topics/immunology-and-microbiology/cells>. Mixtures of human <https://www.sciencedirect.com/topics/immunology-and-microbiology/human> (HEK) and mouse <https://www.sciencedirect.com/topics/immunology-and-microbiology/mouse> (3T3) cells were analyzed by Drop-seq at the concentrations shown. The scatter plot shows the number of human and mouse transcripts associating to each STAMP. Blue dots indicate STAMPs that were designated from these data as human-specifiic (average of 99% human transcripts); red dots indicate STAMPs that were mouse-specific (average 99%). At the lower cell concentration, one STAMP barcode (of 570) associated with a mixture of human and mouse transcripts (A, purple). At the higher cell concentration, about 1.9% of STAMP barcodes associated with mouse-human mixtures (B). Data for other cell concentrations and a different single-cell analysis <https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/single-cell-analysis> platform are in Figures S3 <https://www.sciencedirect.com/science/article/pii/S0092867415005498#figs3>B and S3C.

-Jiom

**Comment by DawnEve** [comment]
Thank you for your advise!
After reading the dropseq cookbook, at the last section titled “Mixed-species plots”, my plot looks alitter right now, thought the C1 data doesnot have UMI.
1.STAR: mapping to hg19_mm10
2.from MAPQ=255 lines, count HUMAN or MOUSE for each cell

samtools view c01_ROW02_Aligned.sortedByCoord.out.bam|awk '$5==255{print $3\t$5}'|cut -c1-5|sort|uniq -c|xargs
## 112 ERCC_ 4925 HUMAN 27605 MOUSE

![hg19_mm10_2](https://user-images.githubusercontent.com/5974903/57935058-88dbc100-78f3-11e9-969a-080896a33555.png)
