### ISSUE TITLE
Retrieve Alignment stats (*Log.final.out)

### ISSUE THREAD

**Issue by ogarmar3** [broadinstitute/Drop-seq#138]
Hello,

I lost the STAR Log.final.out files for some samples. Is there a way to retrieve that information from the *final.bam file generated by DetectBeadSynthesisErrors? Or do I have to run the alignment again.

Thank you,

Marcos

**Comment by alecw** [comment]
Hi @ogarmar3 ,

Our standard pipeline does not read that file, so most of that information is not captured.  

Regards, Alec

**Comment by ogarmar3** [comment]
I guess running Alignment again is the way to go.
Thank you, Alec
