### ISSUE TITLE
BamTagHistogram reports more barcodes than expected

### ISSUE THREAD

**Issue by seb-mueller** [broadinstitute/Drop-seq#142]
### Affected tool(s)
BamTagHistogram

### Affected version(s)
2.0.0 (latest from [bioconda]( https://bioconda.github.io/recipes/Drop-seq_tools/README.html?highlight=dropseq_tools))

### Description 
Given a Drop-Seq dataset in which we had used an estimated 2000 ChemGenes beads within a single PCR to create a library for NGS, I followed drop-seq tools mostly with default parameters, such as `Running BamTagHistogram` as follows

```
BamTagHistogram INPUT=results/samples/sample1/final.bam OUTPUT=results/logs/dropseq_tools/sample1_hist_out_cell.txt TAG=XC MINIMUM_MAPPING_QUALITY=10    FILTER_PCR_DUPLICATES=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT
```

which results in a lot more barcodes than expected (~200,000):

```
wc -l results/logs/dropseq_tools/sample1_hist_out_cell.txt
191763
```

Even only considering barcodes with at least 10 reads there are around 23000 left(Total number of reads are obout 7 million).

This is a lot more than I'd suspect given the barcodes were repaired etc using the standard workflow (i.e. DetectBeadSubstitutionErrors, ) as below which is supposed to detect and repair errors in cell barcodes. 

Assuming these barcodes have already been corrected and that in a perfect world 2000-ish beads should give us 2000-ish barcodes, what are all of these other barcodes beyond 2000?"
Maybe there are paramters or so to correct or collapse barcodes even further?

The complete workflow is from dropSeqPipe in the rule [snakemake file](https://github.com/Hoohm/dropSeqPipe/blob/develop/rules/map.smk)

#### Steps to reproduce
The commands below we run before `BamTagHistogram`
```
DetectBeadSubstitutionErrors -m 10g        I=results/samples/sample1/gene_exon_tagged.bam        O=results/samples/sample1/gene_exon_tagged_bead_sub.bam        OUTPUT_REPORT=results/logs/dropseq_tools/sample1_beadSubstitutionReport.txt        OUTPUT_SUMMARY=sample1_beadSubstitutionSummary.txt
```

```
DetectBeadSynthesisErrors -m 10g        INPUT=results/samples/sample1/gene_exon_tagged_bead_sub.bam        OUTPUT=results/samples/sample1/final.bam        OUTPUT_STATS=results/logs/dropseq_tools/sample1_synthesis_stats.txt        SUMMARY=results/logs/dropseq_tools/sample1_synthesis_stats_summary.txt        NUM_BARCODES=200        PRIMER_SEQUENCE=CCTACACGACGCTCTTCCGATCT        
```

#### Expected behavior
Barcodes should have been corrected/collapsed to be in the same ballpark figure as the 2000 input beads (2k).

#### Actual behavior
200k were reported even after correction. I'm aware that PCR etc will introduce error and some will not be able to be corrected but despite that I did not expect that many barcodes.

Not sure if this is a bug of wrong set of parameters or even completely expected.

**Comment by jamesnemesh** [comment]
Hi @seb-mueller ,

This is completely expected.  We clean up many errors, but we don’t even try to look at beads with < 20 reads (because there isn't enough data in them to make a guess as to how to repair them), of which there are many, which is no doubt where most of your spurious cell barcodes appear.

A different way to think about this would be to look at where you sequencing bandwidth went.  Is > 50% of it on your expected set of cell barcodes (did you do cell selection?). You should probably review the dropseq cookbook: https://github.com/broadinstitute/Drop-seq/blob/v2.3.0/doc/Drop-seq_Alignment_Cookbook.pdf.

**Comment by seb-mueller** [comment]
Hi @jamesnemesh ,

Thanks for the quick response. Indeed, 50% of the reads are assigned to about the expected number of cell barcodes (i.e. ~40).

And indeed, there wasn't that many barcodes corrected (125) in those steps as shown below the `beadSubstitutionReport.txt` 
```
# FILTER_AMBIGUOUS=true
# MIN_UMIS_PER_CELL=20
# UMI_BIAS_THRESHOLD=20
# EDIT_DISTANCE=20
#
# TOTAL_BARCODES_TESTED=100425
# BARCODES_COLLAPSED=125
# ESTIMATED_UMIS_COLLAPSED=21684
# AMBIGUOUS_BARCODES=176
# ESTIMATED_AMBIGUOUS_UMIS=31025
# POLY_T_BIASED_BARCODES=82
# POLY_T_BIASED_BARRCODE_UMIS=3323
# POLY_T_POSITION=8
intended_barcode	neighbor_barcode	intended_size	neighbor_size	position	intended_base	neighbor_base	repaired
GAGTTTTGGGCG	GAGTTTTGGGCC	371	202	12	G	C	FALSE
AGTGCGGTTTGG	AGTGCGGTTTGT	195	160	12	G	T	FALSE
ACAAACGCCAAG	ACAAACGACAAG	36	31	8	C	A	TRUE
TGGGTATAGGTG	TGGGTATAGGTC	2711	2571	12	G	C	FALSE
AGTAGGATATGG	AGTAGGATATGC	550	259	12	G	C	FALSE
...
``` 
Having studied the cookbook, it seems the `systematic errors` are first identified (and corrected) by gathering evidence form sufficient depth (20 reads you mentioned) in order to distinguish them from `sequencing errors`.

One thing wasn't quite clear to me though: 
Are sequencing errors within the barcode also being corrected (i.e. by merging barcodes with a hamming distance of 1 together)? I would have expect this to strategy to have a lot of barcodes absorbed into the "real" ones (which might or might not be given by a whitelist).
However I don't know if this would even be a sensible strategy since I couldn't find clear literature on this apart from [this one](https://cgatoxford.wordpress.com/2017/05/18/estimating-the-number-of-true-cell-barcodes-in-single-cell-rna-seq/)

**Comment by jamesnemesh** [comment]
There are two barcodes, a cell barcode and a UMI barcode.  

For the cell barcode, we perform collapse as mentioned in the cookbook, which includes collapse performed with both hamming distance AND levenshtein distance (to find insertion/deletion events).  Note that only certain patterns in the data are actually collapsed - we want to collapse systematic errors in the synthesis step, not every single random PCR error.  I’d rather discard PCR errors by not selecting those barcodes than greedily collapse the data from those barcodes into your cell barcodes, as by chance you’ll observe barcodes at ED=1 to your main barcode very frequently.  The collapse steps have been validated to make sense biologically - if you were to run a mixture of two organisms in a dropseq experiment and knew the organism of origin for each cell, you wouldn’t want to collapse a mouse and a human cell together, even though they were at a low edit distance, as one of the cells could not have been generated by the other.

For the UMI barcode?  In that case we collapse UMIs within hamming distance of 1 within the same cell barcode.  This occurs on the fly when appropriate for programs like DigitalExpression.

Something to try out with your data:  Plot these two metrics against each other (each point represents a single cell).

1) On the X axis, the log10(number of transcripts per cell)
2) On the Y axis, the log10 (reads per cell / transcripts per cell)


The cluster of points in the middle with the highest density are the empty beads, the cluster to the far right (log10 UMIs > ~4.5) contains your cells.  

You could also try to NOT execute the cleanup steps and plot this figure, to see how cleanup effects this style of cell selection.

-Jim

**Comment by seb-mueller** [comment]
Thanks so much for this explanation and sorry for the nitpicking but this pretty much explains and reasons what's happening, especially this statement:
> I’d rather discard PCR errors by not selecting those barcodes than greedily collapse the data from those barcodes into your cell barcodes, as by chance you’ll observe barcodes at ED=1 to your main barcode very frequently.

I'll close this comment, but nevertheless ask one last (a bit off-topic question): Is it possible to force to greedily collapse `ED=1` into their main barcode so it is reflected in the output of `BamTagHistogram` (`BamTagHistogram` doesn't seem to have that option as far as I can tell). This would be to check how many barcodes would remain.

**Comment by jamesnemesh** [comment]
You might explore:
CollapseBarcodesInPlace
CollapseTagWithContext
ComputeUMISharing

These are all public, but since the conda distribution didn't seem to update, you'd need to retrieve our latest release.

This is far past the scope of anything but you playing with the data to explore this space (so I'm not going to keep this conversation going), but there's some pretty interesting tools to do so.

-Jim

**Comment by alecw** [comment]
Plot suggested in @jamesnemesh comment of 8/20:

![image](https://user-images.githubusercontent.com/266575/66507927-218afd00-ea9e-11e9-96ec-2ebf391d06b5.png)
