### ISSUE TITLE
Use of barcode whitelist to determine accuracy and correction of barcodes.

### ISSUE THREAD

**Issue by rgunaratna** [broadinstitute/Drop-seq#149]
Hi James and Alec,

Thanks for developing the Drop-seq tools and the modifications. I was wondering whether you are planning to incorporate into the tools **the ability to check the extracted barcodes against a user-provided barcode whitelist (as in cell ranger by 10X) and perform barcode corrections as well as UMI quantification based on the user-provided barcodes.**

Best,
Ramesh

**Comment by alecw** [comment]
Hi Ramesh,

We don't have plans to do all of that, but we have a tool that will get you part of the way:

`FilterBamByTag TAG_VALUES_FILE=your_10X_whitelist TAG=XC ACCEPT_TAG=true`

This will discard reads that don't match the cellular indices in the whitelist.

Regards, Alec

**Comment by rgunaratna** [comment]
Thanks, Alec. I really appreciate your prompt reply.

Best,
Ramesh
