### ISSUE TITLE
BamTagHistogram gives same results for setting filter_pcr_duplicates either true or false 

### ISSUE THREAD

**Issue by seb-mueller** [broadinstitute/Drop-seq#157]
### Affected tool(s)
_Tool name(s), special parameters?_

### Affected version(s)
- Latest public release version [2.3.0 and 2.0.0 (haven't tested any other versions)] 

### Description 
Running the below  BamTagHistogram using the XC tag as follows with both  `FILTER_PCR_DUPLICATES`: 
```
BamTagHistogram INPUT=sample.bam OUTPUT=hist_false.txt TAG=XC MINIMUM_MAPPING_QUALITY=10 FILTER_PCR_DUPLICATES=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT

BamTagHistogram INPUT=sample.bam OUTPUT=hist_true.txt  TAG=XC MINIMUM_MAPPING_QUALITY=10 FILTER_PCR_DUPLICATES=true  VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT
```
Result in identical output (`hist_true.txt` and `hist_false.txt`)

#### Steps to reproduce
Run the above commands on any bam file (generated following the cookbook)

I've followed the cookbook and seem to have all necessary tags.
The first entry of the bam file is below:

```
NB501820:111:H5HY2BDXX:2:12103:25093:10180      0       1       14072   0       1S105M9S        *       0       0       ATCACTACCTCTCAACCACTTGAGCAAACTCCAAGACATCTTCTTCACAAACACAAGCAATTGTGACAAGGGCCAGTAGGCTCTCAGCATGACTAGTGTTAGAGACACCGTGTCT   AA</AE///<AAE<<///A<//AA/A/EE<A/<6/AEEEEEAA6AA////<E/6//<<A</6//6//6A/////E/<AA<EAAAEA//A</<<EE/<//AEEEAEE/<E<//<AA   XC:Z:AGAACCTTTGCT       XF:Z:CODING     NH:i:6 HI:i:1  XM:Z:GGGCGGAG   nM:i:10 AS:i:83 gf:Z:CODING     gn:Z:DDX11L1    gs:Z:+
```

#### Expected behavior
Maybe I'm missing something and this is desired behaviour, but I'd expect `hist_true.txt` should have fewer counts per barcode than `hist_false.txt`.

The help is not clear on this parameter, it only says:

`FILTER_PCR_DUPLICATES=Boolean          Filter PCR Duplicates.  Default value: false`

So even if desired, the help could benefit from more details or even examples etc.

**Comment by jamesnemesh** [comment]
DropSeq doesn't use PCR duplicates, which are specifically for genomic reads, so it's working as intended.  This tool can also be run on BAMs that assay DNA aligned with bwa (for example).  In that case, you'd need to mark PCR duplicates in your genomic pipeline.

**Comment by seb-mueller** [comment]
Thanks. I'd mistaken this for UMI based PCR duplication identification (in some dropSeq protocols, there are several PCR rounds). 

It seems `BamTagHistogram` is reporting the number reads per barcode. Is it possible to have the UMI count reported instead, much like the `OUTPUT_READS_INSTEAD` option for `DigitalExpression`?

**Comment by jamesnemesh** [comment]
Even if there are several PCR rounds, you do de-duplication via UMIs, not PCR duplicates.

If you want the number of UMIs, then you’re asking about the definition of what a UMI unique in:
A cell, a gene mapping, and a unique UMI sequence.

This sounds like Digital Expression.  We already have that tool.

-Jim

**Comment by seb-mueller** [comment]
Thats exactly my point. I'm looking for a UMI based de-duplication count histogram. As written above, I'm aware that `DigitalExpression` can do this, but is `BamTagHistogram` able to output UMI counts (and I've wrongly assumed  FILTER_PCR_DUPLICATES would do this).

Ultimately, I was wondering if the resulting knee plot does look different if based on UMIs rather than reads.

**Comment by jamesnemesh** [comment]
Run DGE with MIN_NUM_READS_PER_CELL=20, and plot the summary.

-Jim

**Comment by seb-mueller** [comment]
Thanks a lot, I'll give this a go.
