### ISSUE TITLE
output barcode collapse information

### ISSUE THREAD

**Issue by ersgupta** [broadinstitute/Drop-seq#159]
Hi,

Is it possible to extract the list of barcodes which were collapsed and what was the barcode assigned to the collapsed barcodes?

Thanks
Saurabh

**Comment by alecw** [comment]
Hi Saurabh,

Which program are you asking about?  Note that DetectBeadSynthesisErrors and DetectBeadSubstitutionErrors both product report file in addition to optionally repairing the BAM.

-Alec

**Comment by ersgupta** [comment]
Hi Alec,

Thanks. Basically I want to extract all the reads for a certain barcode and barcode+umi. So I extract the BC and UMI from the respective tags in the bam file (obtained after DetectBeadSynthesis Errors). In the DigitalExpression matrix step I use EDIT_DISTANCE=1, so I want to know which UMIs were collapsed at this stage.

Thanks
Saurabh

**Comment by jamesnemesh** [comment]
We don't track UMI collapse as an output.  The best you would do is to extract expression using GatherMolecularBarcodeDistributionByGene instead, where you get a list of UMIs with read counts for each cell/gene.  You could run this at EDIT_DISTANCE=0 and EDIT_DISTANCE=1, and run your own edit distance collapse at ED=0, then verify you had the same results as the ED=1 results.

**Comment by ersgupta** [comment]
Thanks. This helps, I will give it a shot.
