### ISSUE TITLE
TagReadWithGeneFunction v2.3.0, java.lang.NullPointerException

### ISSUE THREAD

**Issue by MonkeySylvia** [broadinstitute/Drop-seq#160]
Hi,
I want to tag my aligned bam file with the gene tag by "TagReadWithGeneFunction", but I can't get it running. I can't figure out why either. My "TagReadWithGeneFunction " version is v2.3.0. Thank you in advance for helping!

Here is my bam
```
NB501337:174:HCCKHBGX2:3:22610:11803:1662	16	chr1	1323	6	62M	*	0	0	TTCTCTATTGTTTTGACCTTCAGCAGTGAAAATTAAACACTGAAATTAATCTCTGAAAACTG	//<////</A/////EEE//E<<E6///AA/////6/EAE//E////<//A///E<//AA/6	XC:Z:CAGATGTGGCCA	MD:Z:4T0C34C21	PG:Z:bowtie2	RG:Z:A	NM:i:3	XM:Z:GGGGAAGC	UQ:i:42	AS:i:-9
NB501337:174:HCCKHBGX2:1:11305:16993:3443	16	chr1	1325	1	54M	*	0	0	CTTTATTGTTTTGACCTTCAGCAGTGAAAATTAAACACTGAAATTAATCTCTGA	/EEEAE<<EEEAAEEEEE6EEEEEEAAEEEEAAEE/E//EEEEEEEEEEAAAAA	XC:Z:CAGATGTGGCCA	MD:Z:3C34C15	PG:Z:bowtie2	RG:Z:A	NM:i:2	XM:Z:GGGGAAGC	UQ:i:50	AS:i:-8
NB501337:174:HCCKHBGX2:2:23306:15475:8140	16	chr1	1325	6	49M	*	0	0	CTTTATTGTTTTGACCTTCAGCAGTGAAAATTAAACACTGAAATTAATC	EEE<EEEAEEEAEEEEAEEEEAEEEAEEEEEEEEEEEEEEEEEAA<AAA	XC:Z:CAGATGTGGCCA	MD:Z:3C34C10	PG:Z:bowtie2	RG:Z:A	NM:i:2	XM:Z:GGGGAAGC	UQ:i:63	AS:i:-9
```
here is my code
`Drop-seq_tools-2.3.0/TagReadWithGeneFunction INPUT=ZF30-DS5.realigned.barcoded.bam OUTPUT=ZF30-DS5.realigned.genebarcoded.bam GENE_FUNCTION_TAG=null READ_FUNCTION_TAG=null ANNOTATIONS_FILE=danRer11.gene.nonoverlapte.1123.refFlat &`

and my error message

`23:09:27.733 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/local/workdir/nc499/tools/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
23:09:27.742 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
23:09:27.743 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/local/workdir/nc499/tools/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
23:09:27.744 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)

TagReadWithGeneFunction INPUT=ZF30-DS5.bam OUTPUT=test.bam GENE_FUNCTION_TAG=null READ_FUNCTION_TAG=null ANNOTATIONS_FILE=danRer11.gene.nonoverlapte.1123.refFlat    GENE_NAME_TAG=gn GENE_STRAND_TAG=gs USE_STRAND_INFO=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Sun Nov 24 23:09:27 EST 2019] Executing as xxxxx on Linux 3.10.0-957.10.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_212-b04; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.3.0(34e6572_1555443285)
23:09:27.784 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
23:09:28.323 WARN  IntelDeflaterFactory - IntelDeflater is not supported, using Java.util.zip.Deflater
[Sun Nov 24 23:09:28 EST 2019] org.broadinstitute.dropseqrna.metrics.TagReadWithGeneFunction done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.NullPointerException
	at htsjdk.samtools.SAMTagUtil.makeBinaryTag(SAMTagUtil.java:100)
	at htsjdk.samtools.SAMRecord.setAttribute(SAMRecord.java:1425)
	at org.broadinstitute.dropseqrna.metrics.TagReadWithGeneFunction.setAnnotations(TagReadWithGeneFunction.java:205)
	at org.broadinstitute.dropseqrna.metrics.TagReadWithGeneFunction.doWork(TagReadWithGeneFunction.java:121)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
`

**Comment by alecw** [comment]
Hi @MonkeySylvia ,

This problem is cause by this command-line argument:
`GENE_FUNCTION_TAG=null`
This program assigns a value to whatever GENE_FUNCTION_TAG you specify.  It doesn't make sense to set GENE_FUNCTION_TAG to null.

Regards, Alec

**Comment by MonkeySylvia** [comment]
That fixed the issue, thank you Alec!
Sylvia
