### ISSUE TITLE
Quantification of splicing isoforms with DGE

### ISSUE THREAD

**Issue by jdperez101** [broadinstitute/Drop-seq#163]
Hi,
Is there a way for DGE to output the counts of the individual transcripts of every gene instead of the gene level counts? Since the summary file contains a column with NUM_TRANSCRIPTS, I assume this is been calculated already, no?
Thanks,
Julio

**Comment by jamesnemesh** [comment]
DGE is calculated that the gene level, due to the fact that DropSeq (and 10x) are 3’ biased assays.  
This means that the assay will not see many of the alternate exons that are closer to the 5' end of each gene model, making isoform level assignments difficult.

**Comment by jdperez101** [comment]
Thanks for your quick response James! I understand. What I am actually interested on alternative 3'UTRs, so transcript level quantification would still be useful. Any suggestion on how to obtain such quantification?

**Comment by jamesnemesh** [comment]
We don’t have that tool built in directly.  What you might look at for alternate 3’ UTRs would be polyA trim sites in the reads, which should pile up at the ends of genes.  You might cluster those reads across UMIs of each cell, then across cells, to look for alternative UTRs.

I’ve done some exploration in this area, but the signal is noisier than I’d like at the moment, and other needs have been more pressing.

-Jim

**Comment by jdperez101** [comment]
Got it, many thanks!
