### ISSUE TITLE
Error: DigitalExpression 

### ISSUE THREAD

**Issue by alicelee07** [broadinstitute/Drop-seq#164]
Hello,
I got an error message when I was running DigitalExpression.

My command: 
DigitalExpression -I final.bam -O final.dge.txt.gz -SUMMARY gene.final.dge.summary.txt

Error message:
15:58:54.909 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/dropSeq/Drop-seq_tools-2.3.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
[Mon Dec 16 15:58:55 EST 2019] DigitalExpression SUMMARY=/dropSeq/dropseq_output/gene.final.dge.summary.txt OUTPUT=/dropSeq/dropseq_output/final.dge.txt.gz INPUT=/dropSeq/dropseq_output/final.bam    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf STRAND_STRATEGY=SENSE LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Dec 16 15:58:55 EST 2019] 3.10.0-327.3.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_192-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.3.0(34e6572_1555443285)

**ERROR	2019-12-16 15:58:55	DigitalExpression	Running digital expression without somehow selecting a set of barcodes to process no longer supported.
[Mon Dec 16 15:58:55 EST 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=32505856**

I checked if my BAM file aligned with STAR properly by counting the number of HQ aligned reads in my BAM: 
samtools view -q 10 final.bam|wc -l
 **16637314**

Also, checked if they are properly tagged:
samtools view -q 10 final.bam |grep gn:Z |head -n 5
**A00447:HGC5LDMXX180801:HGC5LDMXX:1:1359:12292:25567	16	HUMAN_1	91525	255	50M	*	0	0	TGTTTCATTGTTGTTGTTTAGTTTGTTTTTTTTTTTCTCCAACTTTGTGC	FFFFFFFFFFFF:FFFFFFFFF:F:F,FF:FF:FF:FFFFFFF:FFF:FF	XC:Z:GGTATACGTATG	MD:Z:11G13C0G23	XF:Z:CODING	PG:Z:STAR	RG:Z:A	XG:Z:RP11-34P13.7	NH:i:1	NM:i:3	XM:Z:GGCCGGGT	UQ:i:85	AS:i:43	gf:Z:CODING	gn:Z:RP11-34P13.7	gs:Z:-
A00447:HGC5LDMXX180801:HGC5LDMXX:1:2449:3043:21230	0	HUMAN_1	125381	255	50M	*	0	0	CCATCTGATTATTGTATGTTATTTTTTCCCCAACGTTTAGACTACACAAT	FFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	XC:Z:GTGTGCTAGTCC	MD:Z:50	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	XG:Z:RP11-34P13.7	NH:i:1	NM:i:0	XM:Z:ACTCTAGC	UQ:i:0	AS:i:49	gf:Z:INTRONIC	gn:Z:RP11-34P13.7	gs:Z:-
A00447:HGC5LDMXX180801:HGC5LDMXX:1:2449:4426:18051	0	HUMAN_1	125381	255	50M	*	0	0	CCATCTGATTATTGTATGTTATTTTTTCCCCAACGTTTAGACTACACAAT	FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	XC:Z:GAGTGCTAGTCC	MD:Z:50	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	XG:Z:RP11-34P13.7	NH:i:1	NM:i:0	XM:Z:ACTCTAGC	UQ:i:0	AS:i:49	gf:Z:INTRONIC	gn:Z:RP11-34P13.7	gs:Z:-
A00447:HGC5LDMXX180801:HGC5LDMXX:1:2320:25843:29778	16	HUMAN_1	127494	255	50M	*	0	0	ATAATCTACATCTTTAATGTATGCATATAGCATAGCTAATGTACTATCCC	FFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF,	XC:Z:GCCATCAAGATC	MD:Z:50	XF:Z:INTRONIC	PG:Z:STAR	RG:Z:A	XG:Z:RP11-34P13.7	NH:i:1	NM:i:0	XM:Z:GAGGCCGA	UQ:i:0	AS:i:49	gf:Z:INTRONIC	gn:Z:RP11-34P13.7	gs:Z:-
A00447:HGC5LDMXX180801:HGC5LDMXX:1:1459:7663:28698	16	HUMAN_1	134990	255	50M	*	0	0	AGAGGCTGCCGGAAGGGAAAAACAGGGCCTGGAATGGCCGACATGAGGAA	,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFF	XC:Z:GTCCAATACCCC	MD:Z:42G7	XF:Z:UTR	PG:Z:STAR	RG:Z:A	XG:Z:AL627309.1	NH:i:1	NM:i:1	XM:Z:GAGAAGGT	UQ:i:37	AS:i:47	gf:Z:UTR	gn:Z:AL627309.1	gs:Z:-**

Could you please help me how I can fix this error?
Thank you!

**Comment by jamesnemesh** [comment]
This bit is important:

> ERROR	2019-12-16 15:58:55	DigitalExpression	Running digital expression without somehow selecting a set of barcodes to process no longer supported.
> 

The program needs to know which barcodes in your data set you want to see.  To start, try NUM_CORE_BARCODES=10.  You’ll get out the 10 barcodes with the most reads (which is usually the 10 barcodes with the greatest number of transcripts.)

Once you verify that works, then figure out what you want set of barcodes you want to extract.  There are a number of options available - lists of barcodes in a file, all barcodes that have more than X reads/transcripts/genes, etc.

-Jim

**Comment by alicelee07** [comment]
I tried NUM_CORE_BARCODES=10 and it's working now. Thank you for your help!
