### ISSUE TITLE
Mixed-species data filtering

### ISSUE THREAD

**Issue by pavsol** [broadinstitute/Drop-seq#181]
Hello,
I cannot find any instruction about the about how to filter out the STAMPs which have the reads mapped to both species after it was aligned to the mega-reference (I use human and A. thaliana). I need to retain only those STAMPs which have at least 98 % reads mapped to A. thaliana.

Thank you for any advice.
Pavel

**Comment by jamesnemesh** [comment]
Hi,

Can you create the mixed-species plot as detailed in the cookbook?  https://github.com/broadinstitute/Drop-seq/blob/master/doc/Drop-seq_Alignment_Cookbook.pdf <https://github.com/broadinstitute/Drop-seq/blob/master/doc/Drop-seq_Alignment_Cookbook.pdf>. 

Select the cells that where no one organism explains more than <X>% of the total number of UMIs.  Turn that into a file with the list of barcodes you want, and use that as CELL_BC_FILE argument to DigitalExpression.

-Jim

**Comment by pavsol** [comment]
Hi Jim,
thank you. I created the plot and it is clear now. I have just one more minor question:
What value should I use for NUM_CORE_BARCODES when I run DigitalExpression with the CELL_BC_FILE?
I created cumulative distribution plots and selected the value independently for each organism according to the "knee" position. However, I am not really sure if its correct.

**Comment by jamesnemesh** [comment]
You don’t need to use the NUM_CORE_BARCODE parameter at all.  You’ll extract exactly the set of cells in the CELL_BC_FILE.

-Jim

**Comment by pavsol** [comment]
Crystal clear now, thank you!
