### ISSUE TITLE
DigitalExpression command problem

### ISSUE THREAD

**Issue by cisella** [broadinstitute/Drop-seq#185]
### Instructions

Dear mantanier I have a problem when launching DigitalExpression command on file generated according to the pipeline "ddSeeker_dropSeq_tools.sh". 
when I enter the following command:

./DigitalExpression  -O ~/analysis/single_cells/prova/merged.bam -O ~/analysis/single_cells/prova/merged.dge -SUMMARY ~/analysis/single_cells/prova/gene.final.dge.summary.txt

I receive back this message, seemingly suggesting that I am not properly inputing the right parameters. 

can you help me?

--
Claudio

**Comment by alecw** [comment]
Hi Claudio,

The error message doesn't appear in this report, so it's hard to know what the problem is.  By default, we use Picard old-style command line conventions, i.e. `OPTION=value` instead of `-OPTION value`.  You might also ask the author of ddSeeker.  I'm not familiar with their pipeline.

Regards, Alec

**Comment by cisella** [comment]
Hi Alec,

here it is the output. as you can see it is not really an error, rather an improper input of the files

./DigitalExpression -NUM_CORE_BARCODES=10 -O ~/analysis/single_cells/prova/merged.bam -O ~/analysis/single_cells/prova/merged.dge -SUMMARY ~/analysis/single_cells/prova/gene.final.dge.summary.txt -v
USAGE: ./DigitalExpression [-m <jvm_heap_size>] [-v] program args...
       -m <jvm_heap_size> (default 4g)
       -v echo final command line before executing

Program options:
USAGE: DigitalExpression [options]

Measures the digital expression of a library.  Method: 1) For each gene, find the molecular barcodes on the exons of
that gene.  2) Determine how many HQ mapped reads are assigned to each barcode.  3) Collapse barcodes by edit distance.
4) Throw away barcodes with less than threshold # of reads. 5) Count the number of remaining unique molecular barcodes
for the gene.This program requires a tag for what gene a read is on, a molecular barcode tag, and a exon tag.  The exon
and gene tags may not be present on every read.When filtering the data for a set of barcodes to use, the data is
filtered by ONE of the following methods (and if multiple params are filled in, the top one takes precidence):1)
CELL_BC_FILE, to filter by the some fixed list of cell barcodes2) MIN_NUM_GENES_PER_CELL 3) MIN_NUM_TRANSCRIPTS_PER_CELL
4) NUM_CORE_BARCODES 5) MIN_NUM_READS_PER_CELL  
...

**Comment by alecw** [comment]
Hi Claudio,

OK, I see what is going on.  Our wrapper scripts are not able to handle the dash option style.  You need to use the equal sign style.  Also, the BAM file should be an input, not an output.  Your command line should look something like this:

```
./DigitalExpression I=~/analysis/single_cells/prova/merged.bam O=~/analysis/single_cells/prova/merged.dge SUMMARY=~/analysis/single_cells/prova/gene.final.dge.summary.txt
```

Regards, Alec
