### ISSUE TITLE
ConvertToRefFlat error due to 'Missing gene_name' of the gtf file

### ISSUE THREAD

**Issue by Kaj-cyber** [broadinstitute/Drop-seq#206]
Dear Drop-seq maintainer,

I'm very naive to Drop-seq analysis and try to follow with the cookbook kindly provided in this package. I've just installed the latest version deseq_tools in conda. I've downloaded the canine genome sequence (CanFam3.1.fa) and gtf (CanFam3.1.gtf) file from ensembl. Following the instruction provided in the cookbook, I can make the dict file (CanFam3.1.dict). However I fail to create the refFlat file. I use the command as following:

`ConvertToRefFlat \
ANNOTATIONS_FILE=CanFam3.1.gtf \
SEQUENCE_DICTIONARY=CanFam3.1.dict \
OUTPUT=CanFam3.1.refFlat \
TMP_DIR=/tmp`

Then I've got the error as follows:
`15:06:32.021 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/vetmed/kajbin/anaconda3/share/dropseq_tools-2.3.0-0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Aug 25 15:06:32 ICT 2020] ConvertToRefFlat ANNOTATIONS_FILE=CanFam3.1.gtf SEQUENCE_DICTIONARY=CanFam3.1.dict OUTPUT=CanFam3.1.refFlat TMP_DIR=[/tmp]    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Aug 25 15:06:32 ICT 2020] Executing as vetmed@vetmed-vm on Linux 5.3.0-53-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.3.0(34e6572_1555443285)
[Tue Aug 25 15:06:32 ICT 2020] org.broadinstitute.dropseqrna.annotation.ConvertToRefFlat done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" picard.annotation.AnnotationException: Invalid GTF line: 
chrX    ensembl gene    21422   25435   .       +       .       gene_id "ENSCAFG00000039510"; gene_version "2"; gene_source "ensembl"; gene_biotype "lncRNA";
Problems:
Missing gene_name
        at org.broadinstitute.dropseqrna.annotation.GTFParser.next(GTFParser.java:97)
        at org.broadinstitute.dropseqrna.annotation.GTFParser.next(GTFParser.java:39)
        at htsjdk.samtools.util.PeekableIterator.advance(PeekableIterator.java:71)
        at htsjdk.samtools.util.PeekableIterator.<init>(PeekableIterator.java:38)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.<init>(FilteredIterator.java:43)
        at org.broadinstitute.dropseqrna.utils.FilteredIterator.<init>(FilteredIterator.java:48)
        at org.broadinstitute.dropseqrna.annotation.GTFReader$FilteringGTFParser.<init>(GTFReader.java:113)
        at org.broadinstitute.dropseqrna.annotation.GTFReader$FilteringGTFParser.<init>(GTFReader.java:111)
        at org.broadinstitute.dropseqrna.annotation.GTFReader.load(GTFReader.java:78)
        at org.broadinstitute.dropseqrna.annotation.GTFReader.load(GTFReader.java:74)
        at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadGTFFile(GeneAnnotationReader.java:67)
        at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadAnnotationsFile(GeneAnnotationReader.java:51)
        at org.broadinstitute.dropseqrna.annotation.GeneAnnotationReader.loadAnnotationsFile(GeneAnnotationReader.java:61)
        at org.broadinstitute.dropseqrna.annotation.ConvertToRefFlat.doWork(ConvertToRefFlat.java:71)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)`

As far as I guess, the issue should be about the 'Missing gene_name' of my gtf file.
Could you please show me how to fix this?  I must confess that I'm a biologist, and are quite poor at coding. It would be very kind of you if an example code could be provided.

With respects,
Kaj

**Comment by alecw** [comment]
Hi Kaj,

The program requires gene_name.  Can you check to see if all the entries lack gene_name?  Maybe it's just the lncRNAs.  Try running this:
`fgrep -cv gene_name CanFam3.1.gtf`
This will return a count of the lines that don't contain gene_name.  When I run it on another gtf, I get a small count, like 5, because there are some header lines at the beginning of the file.  Also run this:
`wc -l  CanFam3.1.gtf`
to get a count of all the lines in your gtf.  If you find that there are many lines that have gene_name, but some that do not, you can look at the first few that are missing gene_name with this:
`fgrep -v gene_name CanFam3.1.gtf | head`
If those annotations are for gene_biotypes you don't mind filtering out, then they can be filtered out of the gtf before invoking ConvertToRefFlat.

Regards, Alec

**Comment by Kaj-cyber** [comment]
> `gtf`
Thank you very much Alec!!
I've tried your grep commands, and I'm thinking that the problem is actually due to the gtf file itself.
`fgrep -cv gene_name CanFam3.1.gtf`

`101342`


`wc -l CanFam3.1.gtf`
`1146843`

When observing the line with gene_name using your command, I've got
`fgrep -v gene_name CanFam3.1.gtf | head`

`1       ensembl exon    363607  364092  .       +       .       transcript_id "transcript:ENSCAFT00000000003"; gene_id "gene:ENSCAFG00000000002";
1       ensembl exon    364717  365091  .       +       .       transcript_id "transcript:ENSCAFT00000000003"; gene_id "gene:ENSCAFG00000000002";
1       ensembl CDS     363607  364092  .       +       0       transcript_id "transcript:ENSCAFT00000000003"; gene_id "gene:ENSCAFG00000000002";
1       ensembl CDS     364717  365091  .       +       0       transcript_id "transcript:ENSCAFT00000000003"; gene_id "gene:ENSCAFG00000000002";
1       ensembl exon    439463  439629  .       +       .       transcript_id "transcript:ENSCAFT00000072789"; gene_id "gene:ENSCAFG00000041462";
1       ensembl exon    440182  440398  .       +       .       transcript_id "transcript:ENSCAFT00000072789"; gene_id "gene:ENSCAFG00000041462";
1       ensembl CDS     439463  439629  .       +       0       transcript_id "transcript:ENSCAFT00000072789"; gene_id "gene:ENSCAFG00000041462";
1       ensembl CDS     440182  440398  .       +       1       transcript_id "transcript:ENSCAFT00000072789"; gene_id "gene:ENSCAFG00000041462";
1       ensembl exon    693294  693636  .       -       .       transcript_id "transcript:ENSCAFT00000086492"; gene_id "gene:ENSCAFG00000024219";
1       ensembl exon    694890  694963  .       -       .       transcript_id "transcript:ENSCAFT00000086492"; gene_id "gene:ENSCAFG00000024219";`

I also tried the contrary.
`fgrep gene_name CanFam3.1.gtf | head`

`1       ensembl exon    252103  252562  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    254466  254628  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    256197  256329  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    257162  257242  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    261834  261963  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    263524  263678  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    265578  265629  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    266459  266628  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    268251  268338  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";
1       ensembl exon    269066  269135  .       -       .       transcript_id "transcript:ENSCAFT00000000001"; gene_id "gene:ENSCAFG00000000001"; gene_name "ENPP1";`

Would you please tell me what's wrong with the gtf file, and how to fix ti?

Thank you very much in advance!!
Kaj

**Comment by Kaj-cyber** [comment]
@alecw 
Is it ok if I use the other tool like 'GtfToGenePred'. Is the file considered as refFlat?

**Comment by alecw** [comment]
Hi Kaj,

No, bigGenePred format is not the same as refFlat.

I think you have 3 possible paths:

- Filter out the lines in your GTF that lack gene_name;
- Modify your GTF so that you give each line a gene_name;
- Talk to the people who created the GTF and see if they can fix it.

The first two would likely require your finding someone to help you with some scripting.

Regards, Alec

**Comment by Kaj-cyber** [comment]
@alecw 
I successfully create refFlat file after extracting the only lines of GTF with gene_name as follows:
`fgrep gene_name CanFam3.1.gtf > temp.gtf

ConvertToRefFlat \
ANNOTATIONS_FILE=temp.gtf \
SEQUENCE_DICTIONARY=CanFam3.1.dict \
OUTPUT=temp.refFlat
`
However, it also means that I have lost a large number of annotated regions! It would be very nice if there is a code to fill all missing gene_name with those presented in gene_id. My coding skill is too poor to cope up with that, your kind suggestion would be greatly appreciated. For this moment, I might go to your last choice contacting ensembl maintainer to modify the gtf file for me.

This is just my curiosity, could the function itself be modified to use the gene_id? I'm working with mammalian genome, and I'm quite 100% sure that this kind of problem would be issues in gtf files of other species.

**Comment by alecw** [comment]
Hi Kaj,

This doesn't appear to be a widespread problem.  The Drop-seq tools have been around for several years now and I don't recall a report on this issue previously.  I believe that your GTF has more problems than just the gene name.  It also doesn't have transcript name.  If you want to find a Java programmer to submit a pull request, we'll consider it, but it's not a high priority for us to fix it.

Regards, Alec

**Comment by Kaj-cyber** [comment]
@alecw 
According from your advice, I've managed to create new gene_name and transcript_name using gene_id and transcript_id. This could be achieved by 'pygtftk' (https://github.com/dputhier/pygtftk). Assoc. Denis Puthier-whom I gave the overall credit to him kindly provided me guidance as follows:

`# Get the GTF file from canis lupus familiaris
gtftk retrieve -s canis_lupus_familiaris

# Uncompress
gunzip Canis_lupus_familiaris.CanFam3.1.101.chr.gtf.gz

# Get the number of unique gene_id, gene_name, transcript_id, transcript_name  (to check #gene_name < #gene_id; #transcript_name < transcript_id)
gtftk count_key_values -u -i Canis_lupus_familiaris.CanFam3.1.101.chr.gtf -k gene_id,gene_name,transcript_id, transcript_name

# Create new gene_name from as gene_name|gene_id
gtftk merge_attr -i Canis_lupus_familiaris.CanFam3.1.101.chr.gtf -k gene_name,gene_id -d A_NEW_KEY | gtftk del_attr -k gene_name | perl -npe 's/A_NEW_KEY/gene_name/' > Canis_lupus_familiaris.CanFam3.1.101.chr_with_gn.gtf
# Create new transcript_name from as transcript_name|transcript_id
gtftk merge_attr -i Canis_lupus_familiaris.CanFam3.1.101.chr_with_gn.gtf -k transcript_name,transcript_id -d A_NEW_KEY | gtftk del_attr -k transcript_name | perl -npe 's/A_NEW_KEY/transcript_name/' > Canis_lupus_familiaris.CanFam3.1.101.chr_with_gn_tn.gtf

# Check the number of gene_name and gen_id is the same
gtftk count_key_values -u -i Canis_lupus_familiaris.CanFam3.1.101.chr_with_gn_tn.gtf -k gene_id,gene_name,transcript_id, transcript_name

Thank you very much for your kind suggestion
Kaj

**Comment by alecw** [comment]
Thanks, Kaj.  I didn't know about this tool.  I'm glad you got it working.

Regards, Alec
