### ISSUE TITLE
Knee-finding method used in Cell paper

### ISSUE THREAD

**Issue by liameabbott** [broadinstitute/Drop-seq#211]
Hello,

I may be missing it, but I can't seem to find a description of the exact method used to find the "knee" in the cumulative plot to separate STAMPs from cell-less beads in the 2015 *Cell* paper.

The closest thing I found in the supplement was:

> To distinguish cell barcodes arising from STAMPs, rather than those that corresponded to beads never exposed to cell lysate, we ordered our digital expression matrix by the total number of transcripts per cellbarcode, and plotted the cumulative fraction of all transcripts in the matrix for each successively smaller cell barcode.  Empirically, our data always displays a “knee” at a cell barcode number close to the estimatednumber of STAMPs amplified (Figure S3A).  All cell barcodes larger than this cutoff were used in downstream analysis, while the remaining cell barcodes were discarded.

Is this described in further detail somewhere else in the paper/online documentation for Drop-seq Tools that I'm missing?

Thanks!

**Comment by jamesnemesh** [comment]
I'm so sorry, we never answered your question.  

For posterity:

Please look at the dropseq cookbook, page 21.  There's a small section with example code.
https://github.com/broadinstitute/Drop-seq/blob/master/doc/Drop-seq_Alignment_Cookbook.pdf
