### ISSUE TITLE
selection of base range parameter in drop-seq pipeline

### ISSUE THREAD

**Issue by jurtlest** [broadinstitute/Drop-seq#215]
Hi All,

I am currently trying to re-align sc data (recently published but aligned to a much older sequence) using the dropseq pipeline to update what it's aligned to.

What is the rationale for the basis of base range ?? I opted for the default cookbook parameter of 1-12 for XC 13-20 for XM but I figure there's a more sophisticated way in selecting the base range ?

java -jar -Xmx30g ${dropseq_path}/dropseq.jar TagBamWithReadSequenceExtended
INPUT=${path}/${sample[@]}_raw.bam
OUTPUT=${path}/${sample[@]}_unaligned_tagged_barcode.bam
SUMMARY=unaligned_tagged_barcodes.bam_summary.txt
?????? BASE_RANGE=1-6:22-27:43-48 ??????
BASE_QUALITY=10
BARCODED_READ=1
DISCARD_READ=False
TAG_NAME=XC
NUM_BASES_BELOW_QUALITY=1

I appreciate anyone that takes the time to read and consult. Thanks !

**Comment by jamesnemesh** [comment]
Hi,

Those settings are entirely dependent on the chemistry of the experiment.  If you’re running a dropseq experiment as described in the 2015 paper, then the first 12 bases are the cell barcode, and the next 8 the molecular barcode.  If you’re running a recent 10x experiment, they have a 16 base cell barcode and a 12 base molecular barcode.

If you’re realigning data, you may have those cell and molecular tags already on your reads, and you don’t need to run the tagging step.

-Jim

**Comment by jurtlest** [comment]
Thanks James!
