### ISSUE TITLE
CreateIntervalsFiles - STAR needs more RAM

### ISSUE THREAD

**Issue by yechoi942** [broadinstitute/Drop-seq#218]
Hi,

I am running a create_Drop-seq_reference_metadata.sh, and at the CreateIntervalsFiles, the program outputs: 

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 85543555797 and make that much RAM available 

I know that when I am running STAR directly, I can use --limitGenomeGenerateRAM= large enough memory,
but I could not find any option from CreateIntervalsFiles and create_Drop-seq_reference_metadata.sh to increase the RAM for STAR.

Is there a way to change the default value of RAM for STAR, or give an input at the command lines?

Thanks.

**Comment by alecw** [comment]
Hi @yechoi942 ,

That script is very rudimentary.  You can just edit the script and put whatever options you want in there.

Regards, Alec
