### ISSUE TITLE
DigitalExpression: save temporary files for further counting

### ISSUE THREAD

**Issue by ysu2015** [broadinstitute/Drop-seq#220]
Hi,
Thank you for developing this nice tool. 
DigitalExpression taking very long if deal with big dataset. Sometimes we need to redo the counting with different output of cell numbers/cell barcode files and other reasons. I was wondering whether we could save the temporary file after the "BamTagHistogram Processed" step. Then we could only redo the "UMIIterator Processed" if we need to redo the counting afterwards. Very naive thought. Maybe other people have other thoughts about this.

Y

**Comment by jamesnemesh** [comment]
You can run BamTagHistogram separately, get the counts of reads per cell barcode, and then use the CELL_BC_FILE of DigitalExpression to extract data from subsets of cells. If you input a specific list of cell barcodes to extract, DigitalExpression doesn’t run BamTagHistogram for you, which will save you time.

-Jim

**Comment by ysu2015** [comment]
Great. Thank you.

Y
