### ISSUE TITLE
How to Calculate Sequencing Saturation Based on UMI via Drop-seq Tools Output

### ISSUE THREAD

**Issue by zhengyueli98** [broadinstitute/Drop-seq#227]
Hi,

First of all, thank you for developing such a useful tool kit! 

I'm currently working on calculating sequencing saturation based on UMI, but couldn't find details in the cookbook, neither saw any documents with count details generated by drop-seq tools. Just would like to consult if there's any compatible module or software I can use to extract saturation results from the BAM file generated via the drop-seq tools? Or should I work with the matrix.txt directly?

Thank you so much for your time!

Best,
Zhen Li

**Comment by jamesnemesh** [comment]
Hi,

We don’t have a specific program in our public repository that would explicitly support this analysis, but the analysis is fairly straight forward to do (if not a little labor intensive.)

What you’re interested in is the relationship between the number of reads in the experiment and the number of UMIs that you obtain.  While you can’t directly observe what your data would look like at 2x the current sequencing depth, you can make some estimates by downsampling and fitting the data.  Here’s the procedure:

1) Downsample the READS in your BAM file to some lower amounts, such as 25,50,75%,100% of your total reads
2) Run DGE to get the number of UMIs per cell at these downsampled levels
3) Calculate the number of reads per cell at these downsampled levels.
3) Bin the cells into deciles from the largest to the smallest cells.  
4) You now have the number of UMIs you observe in your top 10% of cells, top 20% etc, and you have the number of reads
5) If you plot each decile, you’ll notice the data fits a curve.  We’ve found that a log-linear fit to the data seems to work reasonably well.
6) Based on this fit, you can project out to 1.5x or 2x sequencing coverage for a good guess as to how many more UMIs you would observe if you added additional sequencing.

You might come up with a plot that looks similar to this:



The plot used downsampling from 10-100% of the reads in the BAM at 10% increments, but that may be overkill for your more manual analysis.

We frequently see a small set of cells that appear to have a very different curve than the rest of the data, and it’s hard to guess if those cells are physically larger, if the capture efficiency was better in some subset of cells, contain a doublet that we were not able to computationally screen out, or some combination of all of the above.  

-Jim
