### ISSUE TITLE
VDJ Analysis

### ISSUE THREAD

**Issue by zhengyueli98** [broadinstitute/Drop-seq#254]
Hi,

First of all, thank you so much for developing such a useful tool kit!

I'm currently working on extracting VDJ information out of 5' gene expression (clonotype, contig annotation, etc). May I ask if drop-seq tools have such a function? If not, would you have any suggestions regarding the algorithm usage? I'm afraid we couldn't use CellRanger due to the special PCR primer design and the lack of VDJ enrichment dataset.

Thank you so much for your help!

Best,
Zhen Li

**Comment by jamesnemesh** [comment]
Sorry, we don’t have any support for that sort of work, and as it’s outside of the domains I typically work in, I don’t have any tool suggestions for you.

-Jim

**Comment by snyquist2** [comment]
@zhengyueli98 Not sure if this will help, but you might be able to use part of this pipeline https://github.com/ShalekLab/tcrgo to help with this task.

It is not specifically for the situation you described, but it may be flexible enough to help get you started and depends on some components of DropSeq Tools
