### ISSUE TITLE
GenotypeSperm

### ISSUE THREAD

**Issue by YULEITSINGTAO** [broadinstitute/Drop-seq#264]
Hello there, 

I am wondering if you can share the instruction about the GenotypeSperm function which call the SNP based on sperm sequencing. I appreciate your time and help in advance. 

Thanks
Lei

**Comment by jamesnemesh** [comment]
Hi,

It would be helpful to better understand what you need if you have a more specific question.  For now, let me point to a few resources:

Avery’s code and descriptions of exactly how she performed the analysis here: https://zenodo.org/record/3561080#.YO2d7G4pA8Y <https://zenodo.org/record/3561080#.YO2d7G4pA8Y>

If you invoke GenotypeSperm directly, you’ll see the various arguments you can use to invoke it.  You need a few bits of information:  
1) A BAM file containing your read data
2) A Picard style list of intervals where you want to measure pileups on your data(https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists <https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists>)
3) A list of cell barcodes that represent true cells (and not empty beads) in your experiment

-Jim

**Comment by YULEITSINGTAO** [comment]
Thanks for sharing. I am working on the 1x sperm sequences and I want to call the SNP from sperm sequencing by GenotypeSperm for my downstream analysis. 

Thanks
Lei

**Comment by jamesnemesh** [comment]
Closed as there was no further response.
