### ISSUE TITLE
CreateIntervalFiles

### ISSUE THREAD

**Issue by v-mahughes** [broadinstitute/Drop-seq#316]
When I run the following command: 
bash -x /home/v-mahughes/ex_vivo/Drop-seq_tools-2.5.1/CreateIntervalsFiles SEQUENCE_DICTIONARY=/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/reference.dict REDUCED_GTF=/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/GRCh38.reduced.gtf PREFIX='GRCh38' OUTPUT=/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/intervals/ MT_SEQUENCE='MT'

I get this error: 

Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.RuntimeException: Sequence 'MT' specified on command line but not found in sequence dictionary
        at org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles.createSubsetSamHeader(CreateIntervalsFiles.java:193)
        at org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles.doWork(CreateIntervalsFiles.java:101)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)

I have also tried not wrapping MT_SEQUENCE in string wrappers, but I get the same error. The Drop Seq Alignment cookbook instructs me to use MT for homo sapiens.

**Comment by jamesnemesh** [comment]
Different builds of the genome (unfortunately) use different chromosome names - the original documentation was written for hg19 data.  You have a sequence dictionary file, you should check the name there.  In our hg38 reference, the sequence dictionary line is:

@SQ	SN:chrM	

-Jim

**Comment by v-mahughes** [comment]
Interesting. I think it is SN:chrM for hg19 as well. I just made a reference dict for hg19 and MT also does not work

**Comment by v-mahughes** [comment]
I think it may be SN:chrM for hg19 as well. When I open my reference dict I made for hg19, this is what is shown: @SQ     SN:chr15        LN:102531392    M5:e5645a794a8238215b2cd77acb95a078     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr16        LN:90354753     M5:fc9b1a7b42b97a864f56b348b06095e6     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr17        LN:81195210     M5:351f64d4f4f9ddd45b35336ad97aa6de     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr18        LN:78077248     M5:b15d4b2d29dde9d3e4f93d1d0f2cbc9c     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr19        LN:59128983     M5:1aacd71f30db8e561810913e0b72636d     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr20        LN:63025520     M5:0dec9660ec1efaaf33281c0d5ea2560f     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr21        LN:48129895     M5:2979a6085bfe28e3ad6f552f361ed74d     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chr22        LN:51304566     M5:a718acaa6135fdca8357d5bfe94211dd     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chrX LN:155270560    M5:7e0e2e580297b7764e31dbc80c2540dd     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta
@SQ     SN:chrY LN:59373566     M5:1e86411d73e6f00a10590f976be01623     UR:file:/home/v-mahughes/ex_vivo/preprocess/dropseq_inputs/ucsc-hg19-fasta/ucsc.hg19.fasta

**Comment by v-mahughes** [comment]
Also, @sq SN:chrM is also not being accepted as an MT_Sequence input

**Comment by jamesnemesh** [comment]
I don’t see any reference to a valid MT chromosome in this set.   Is it possible your reference doesn’t include it?

-Jim

**Comment by v-mahughes** [comment]
According to ucsc it only contains chromosomes 1-22, X and Y from UCSC [1] and combines them in order. Can you point me towards a valid hg19 reference set?

**Comment by jamesnemesh** [comment]
You could try:

ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/ <ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/>

Grab human_g1k_v37.fasta.gz.

That will have the MT contig:

gunzip -c human_g1k_v37.fasta.gz |grep ">MT"
>MT gi|251831106|ref|NC_012920.1| Homo sapiens mitochondrion, complete genome

A matching GTF from that time period:

ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz <ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz>

-Jim
