### ISSUE TITLE
AssignCellsToSamples more explicit filtering results

### ISSUE THREAD

**Issue by jamesnemesh** [broadinstitute/Drop-seq#324]
When AssignCellsToSamples iterates through a BAM file, it applies a number of filters to remove BAM records that can't be used.  Sometimes, all records are removed and the program produces no useful output.

This filtering is opaque, and users frequently need help understanding why their reads were removed.  Make this filtering more explicit by tracking the number of reads removed at each stage and reporting the counts of reads removed by each step.

**Comment by thouis** [comment]
Additional suggestion: if 10% of the reads in the .bam are processed, and counts are 0, default to exiting with an error.  Add a flag that suppresses that behavior.

**Comment by jamesnemesh** [comment]
We don't have a way to infer how many reads are in a BAM without taking a pass through the BAM file to gather that, which would be pretty expensive.  

The reads are processed as a nested set of nested iterators.  We could perhaps set some threshold for an absolute number of reads seen without seeing a read that passes a filter, and do something unpleasant like throw an exception that could be caught later and reported out.

**Comment by thouis** [comment]
A threshold (configurable?) for finding a passing read would be sufficient from my POV.

**Comment by jamesnemesh** [comment]
@thouis I've taken a pass at implementing both better logging and a fast-fail mechanism.  The fast fail is still not as fast as I'd like, but it should be an improvement.  The new logging should make it easier to see where reads/sites are being lost as all filters now explicitly report how many reads/sites/records are filtered by a particular test.
