### ISSUE TITLE
The output of DigitalExpress is an empty matrix

### ISSUE THREAD

**Issue by HUPINLI** [broadinstitute/Drop-seq#337]
Hi Alec,
@alecw 

### Instructions

The output of DigitalExpress is an empty matrix.

Command line used to tag the BAM file:

/home/hupinli/tools/Anaconda/envs/R4.1.1/share/dropseq_tools-2.5.1-0/TagReadWithGeneFunction \
O=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/PIPELINE_MAJOR/Flower3_S1_L001/Flower3_S1_L001_gene_exon_tagged.bam \
I=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/PIPELINE_MAJOR/Flower3_S1_L001/Flower3_S1_L001_merged.bam \
ANNOTATIONS_FILE=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/refFlat.refFlat \
CREATE_INDEX=true

/home/hupinli/tools/Anaconda/envs/R4.1.1/share/dropseq_tools-2.5.1-0/DigitalExpression \
O=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/PIPELINE_MAJOR/Flower1_S1_L001/Flower1_S1_L001_gene_expression_matrix.txt.gz \
I=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/PIPELINE_MAJOR/Flower1_S1_L001/Flower1_S1_L001_gene_exon_tagged.bam \
SUMMARY=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/PIPELINE_MAJOR/Flower1_S1_L001/Flower1_S1_L001_gene_dge.summary.txt \
NUM_CORE_BARCODES=5000 \
TMP_DIR=/home/hupinli/workdir/Gerbera_jamesoniiBolus/annotation/Re_annotation/temp

BAM. E.g. :

A00133:668:HLVMGDSX3:1:2575:23981:3818	16	Chr1	883	3	20M	*	0	0	CTAAACCCACCCCCCCGCCC	,F,,,,:F,F,FF:,,,FFF	XC:Z:AGTGACTAGAGAATCT	MD:Z:16C3	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:2	NM:i:1	XM:Z:CGGTTGGACGTA     ZP:i:21	UQ:i:11	AS:i:17
A00133:668:HLVMGDSX3:1:2666:12563:32800	16	Chr1	892	255	4S57M	*	0	0	CCTCCCCCCCCCCCCCCCACCCACCCCCCACCACCCCCCCCCCCCCCCCCCCCCCCCCCCC	,:,,,,,,:,,,,,,,,F,FF,,,,F:,,,,:,:,F,,,,,F,F,FF,FFFFFFFFFFFFF	XC:Z:TCACACCGTATGTCCA	MD:Z:28C3A6A5A0A5A0A3	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:7	XM:Z:AAATTTAAATAG	ZP:i:62	UQ:i:207	AS:i:42
A00133:668:HLVMGDSX3:1:2635:25961:28823	16	Chr1	898	255	39M	*	0	0	CCCCCCCCACCCACCCCCTCCCCCCCCCCGCCCCCCCCC	,,,,,,,,,,,,,,,,,,,,:,,,:,,,,,,,,,F,:F:	XC:Z:AACGTCAGTACGGATG	MD:Z:18C0A6A2C3A5	XF:Z:INTERGENIC	PG:Z:STAR	RG:Z:ANH:i:1	NM:i:5	XM:Z:GTTTTCAGACAA	ZP:i:40	UQ:i:55	AS:i:28

I am wondering how to solve this problem.

thanks,
Pinli Hu

**Comment by alecw** [comment]
Hi @HUPINLI ,

The sample reads you provided were considered intergenic, so they don't have any gene annotation on them.  I wonder if there is something strange with your annotations file, such that it isn't matching any of your reads.  Is it possible to send the annotation for a gene that you might expect to be in your reads, and then use samtools to search for reads that overlap the gene?  

Are there any warning messages in the output of either program?  

Regards, Alec

**Comment by HUPINLI** [comment]
Hi Alec,@alecw

Thank you for your reminding. When I used gtfToGenePred tool, there was an error in the annotation file generated due to my data problem. Now I have successfully eliminated the problem and generated the expression matrix.  I really appreciate your help.

thanks,
Pinli Hu
