### ISSUE TITLE
Dropulation java heap size -m option error

### ISSUE THREAD

**Issue by drneavin** [broadinstitute/Drop-seq#347]
### Tool(s) involved
AssignCellsToSamples and DetectDoublets

### Description 
The help message for AssignCellsToSamples and DetectDoublets indicates that the java heap size can be indicated with the -m parameter:
```
USAGE: /directflow/SCCGGroupShare/projects/DrewNeavin/software/Drop-seq_tools-2.5.1/AssignCellsToSamples [-m <jvm_heap_size>] [-v] program args...
       -m <jvm_heap_size> (default 4g)
       -v echo final command line before executing
```
 but when I try to set this I get the following error:
```
-m is not a recognized option
```
Would be good to update the help text or update so that this option can be used.

Thanks!

**Comment by jamesnemesh** [comment]
Just to check:

When you're invoking tools, are you using invoking the tool with the memory option first?

```
AssignCellsToSamples -m 8g [standard options]
```

If you look at the deployed tool AssignCellsToSamples, it's a shell script that defers to the jar file and passes in your -m option to the typical java heap syntax and then passes on all the other arguments.

```
while getopts ":m:vh" options; do
  case $options in
    m ) xmx=$OPTARG;;

[...]

java -Xmx${xmx} -XX:+UseParallelOldGC -XX:ParallelGCThreads=1 -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=$TMPDIR -jar $jar_deploy_dir/dropseq.jar $progname $*
```

This should be the same as this command, which you could use if you preferred more direct control of other java options.

```
java -Xmx8g -jar dropseq.jar AssignCellsToSamples
```
