### ISSUE TITLE
java.lang.NullPointerException when running DigitalExpression

### ISSUE THREAD

**Issue by fbrundu** [broadinstitute/Drop-seq#38]
Hi,
I am running the DigitalExpression tool (v1.13) but I am encountering an issue:

```
[Wed Sep 26 18:33:04 UTC 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression SUMMARY=sample.count_summary.txt OUTPUT=sample.counts.tsv INPUT=sample.aligned.clean.bam EDIT_DISTANCE=1 NUM_CORE_BARCODES=1000    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Wed Sep 26 18:33:04 UTC 2018] Executing as ubuntu@ip-172-31-81-77 on Linux 4.4.0-1067-aws amd64; OpenJDK 64-Bit Server VM 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13; Picard version: 1.13(7bed8f4_1513008033)
INFO	2018-09-26 18:33:29	BAMTagHistogram	Processed    10,000,000 records.  Elapsed time: 00:00:25s.  Time for last 10,000,000:   25s.  Last read position: 17:64,499,890
INFO	2018-09-26 18:33:54	BAMTagHistogram	Processed    20,000,000 records.  Elapsed time: 00:00:49s.  Time for last 10,000,000:   24s.  Last read position: 7:8,157,375
INFO	2018-09-26 18:34:11	BarcodeListRetrieval	Looking for the top 1000 cell barcodes
INFO	2018-09-26 18:34:11	BarcodeListRetrieval	Selected 1000 core barcodes
INFO	2018-09-26 18:34:11	DigitalExpression	Calculating digital expression for [1000] cells.
[Wed Sep 26 18:34:11 UTC 2018] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 1.12 minutes.
Runtime.totalMemory()=1804599296
Exception in thread "main" java.lang.NullPointerException
	at org.broadinstitute.dropseqrna.utils.readiterators.UmiIteratorWrapper.processRecord(UmiIteratorWrapper.java:99)
	at org.broadinstitute.dropseqrna.utils.readiterators.UmiIteratorWrapper.processRecord(UmiIteratorWrapper.java:38)
	at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.populateOutputQueue(CountChangingIteratorWrapper.java:53)
	at org.broadinstitute.dropseqrna.utils.CountChangingIteratorWrapper.hasNext(CountChangingIteratorWrapper.java:68)
	at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:63)
	at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:58)
	at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:123)
	at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:75)
	at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.digitalExpression(DigitalExpression.java:166)
	at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:150)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
```

I selected 1000 core barcodes by looking at the inflection point of the plot in the documentation:

![rplot001](https://user-images.githubusercontent.com/697622/46101354-b1af1a80-c199-11e8-898e-39f47455aec9.png)

Additionally, these are two lines extracted from the sample BAM file, all the tags needed should be present:

```
sample.7861898	0	1	14105	0	120M	*	0	0	GACAACTTCTACCCCAACACCAGCAATTGTGCCAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCCGAGTCTGTCACTGAACCCCTTTTTGTGGGAGAATATTCCTCCCAT	.AAG....<.<<....GGGGAG<.GG.<AA<G.AGG...<AA.AAAGA.<<.....<.<..<<..<<.<.<<A<A<..<.<<<..<...<.<<.<AAGG.<<<.<<<.<GGGAGGGG.<.	XC:Z:CAGCGGCGCCTA	MD:Z:4T71T13A2T13C12	GE:Z:DDX11L1	PG:Z:STAR	RG:Z:A	NH:i:5	NM:i:5	XM:Z:ATGAGAAA	UQ:i:65	AS:i:108
sample.30615959	0	1	14112	0	2S117M1S	*	0	0	CGTCTACACCAACAACAGAAATTGTACTAAGGGCCATTAGGCTCTCAGCATGACTATTTTTAGAGACCCAGTGTCTATCACTGAAACCTTTTTTGTGGGAGACTATTCCTCCCATCTGCG	...7.<G.<<...<.<G..<A.......<......<..GA...<A....<G.<.<GAAAAAA.<.<.<...<<.<....<<...<A.<AA<..<.<A.G.<<<A.<<.........<<<.	XC:Z:CAGCGGCGCCTA	MD:Z:5C6C3C6G1C41C6G42	GE:Z:DDX11L1	PG:Z:STAR	RG:Z:A	NH:i:5	NM:i:7	XM:Z:ATGAGAAA	UQ:i:91	AS:i:101
```

I think to have defined all the necessary parameters, all the other ones use the defaults. What may be the underlying issue?

**Comment by jamesnemesh** [comment]
Could you check and see if you ran TagReadWithGeneExon for the BAM you submitted.  In particular, you should have BAM tags (GE, GS) to denote the gene and strand of the gene for reads that overlap the exon of a gene in your submitted annotations.  

Are you following the computational cookbook?

http://mccarrolllab.org/wp-content/uploads/2016/03/Drop-seqAlignmentCookbookv1.2Jan2016.pdf <http://mccarrolllab.org/wp-content/uploads/2016/03/Drop-seqAlignmentCookbookv1.2Jan2016.pdf>

-Jim

**Comment by fbrundu** [comment]
Thanks for the prompt response,
Yes I'm following the latest version of computational cookbook.

I want to map both intronic and exonic regions, so I used TagReadWithInterval, with an interval file in which I used the "gene" annotations in the GTF, not the "exon" annotations. I think in a previous version the tool was named TagReadWithGene? (as defined in [the script](https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE97930&format=file&file=GSE97930%5FREADME%2Etxt) for [this published paper](https://www.nature.com/articles/nbt.4038)).

I noticed now that my BAM has the GE annotation but not the strand one (GS). In my case, should I use TagReadWithGeneExon, TagReadWithInterval or both (and in which order)?

Thank you very much.

**Comment by jamesnemesh** [comment]
It sounds like you’ve deviated a bit from the cookbook, which would instruct you to run TagReadWithGeneExon.  This tagger tags both the gene (XIST) as well as the strand of the gene (+/-) so we can match that up against the read’s strand.  We expect in the dropseq protocol that the reads are on the same strand as the gene.  The public release that you downloaded from the website doesn’t support intronic expression.

The current public repository has new tools that handle intronic and exonic expression properly.  In particular we’ve split TagReadWithGeneExon into 2 versions: TagReadWithGeneExonFunction is the old code, for people who want the more simple tagging methodology and rely on it for 3rd party tools, and TagReadWithGeneFunction, which for your purposes replaces TagReadWithGeneExon.  If you check out our code base (we were just trying up the repo this morning to prepare for release, so I’m not sure if it’s officially open as of now or will be very shortly.) you can run TagReadWithGeneFunction on your BAM, then run the new DGE.  You’ll see additional options to extract expression for CODING, UTR, INTRONIC reads, and you can and match as you’d like.

-Jim

**Comment by fbrundu** [comment]
Thanks, it seems to be working now.

**Comment by jolespin** [comment]
I am also getting this error:
```bash
-bash-4.1$ /usr/local/scratch/METAGENOMICS/jespinoz/Dropseq/Drop-seq_tools-1.13/DigitalExpression I=./fastq/Fresh_HJGKNBGX5.clean.bam O=./fastq/Fresh_HJGKNBGX5.dge.txt SUMMARY=./fastq/Fresh_HJGKNBGX5.dge.summary.txt MIN_NUM_TRANSCRIPTS_PER_CELL=1
[Fri Jan 11 23:34:41 EST 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression SUMMARY=./fastq/Fresh_HJGKNBGX5.dge.summary.txt OUTPUT=./fastq/Fresh_HJGKNBGX5.dge.txt INPUT=./fastq/Fresh_HJGKNBGX5.clean.bam MIN_NUM_TRANSCRIPTS_PER_CELL=1    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Fri Jan 11 23:34:41 EST 2019] Executing as jespinoz@lserver2.jcvi.org on Linux 2.6.32-696.18.7.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_121-b15; Picard version: 1.13(7bed8f4_1513008033)
INFO	2019-01-11 23:34:41	BarcodeListRetrieval	Looking for cell barcodes that have at least 1 transcripts
[Fri Jan 11 23:34:42 EST 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=222298112
Exception in thread "main" java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at org.broadinstitute.dropseqrna.utils.readiterators.UmiIteratorWrapper.<init>(UmiIteratorWrapper.java:74)
	at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:120)
	at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:75)
	at org.broadinstitute.dropseqrna.barnyard.GatherMolecularBarcodeDistributionByGene.getNumTranscriptsPerCell(GatherMolecularBarcodeDistributionByGene.java:143)
	at org.broadinstitute.dropseqrna.barnyard.BarcodeListRetrieval.getListCellBarcodesByTranscriptCount(BarcodeListRetrieval.java:192)
	at org.broadinstitute.dropseqrna.barnyard.BarcodeListRetrieval.getCellBarcodes(BarcodeListRetrieval.java:83)
	at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:141)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:94)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
```

Here is the top 2 records of my bam file:
```
HJGKNBGX5:1:11101:10000:10496   4       *       0       0       *       *       0       0       AGACAAGACAAGACCGACGTCTCTAATGTCATAGATAAAGAAGCTAATCTCTTTGATATT    AA///EAEE/</EA//<E<A<//E/E//E/<<//A/AAE/<E/A/A<A//A/////E/A<    XC:Z:AATACCGAGCGA       RG:Z:A  XM:Z:CAGGGTCA
HJGKNBGX5:1:11101:10000:10980   4       *       0       0       *       *       0       0       GTACTCTGCGTTGATACCACTGCTTCCGCGGACAGGCGTGTAGATCTCGGTGGTCGCCGT    A///6//A<</AA////A//E6E<</</A/////<AAAE////////A//AA//</A/</    XC:Z:CTGTCTCTTATA       RG:Z:A  XM:Z:CACATCTC
```

I checked to see if my pipeline ran `TagReadWithGeneExon` and it looks like it did:

```bash
-bash-4.1$ cat fastq/Fresh_HJGKNBGX5.mk | grep "TagReadWithGeneExon"
/usr/local/scratch/METAGENOMICS/jespinoz/Dropseq/Drop-seq_tools-1.13/TagReadWithGeneExon I=./fastq/Fresh_HJGKNBGX5.merged.bam O=./fastq/Fresh_HJGKNBGX5.gene_exon_tagged.bam ANNOTATIONS_FILE=./ref/reference.gtf TAG=GE
```

Do you have any idea of what could be going on?

**Comment by jamesnemesh** [comment]
What version of the code are you on?

In the latest version, you want to run TagReadWithGeneFunction.  If you’re using an BAM tagged by the older system and running new data, you need to re-tag the reads with the latest tagger before you run DGE.

That said, you should never see a NullPointer.  However, the amount of data you submitted is insufficient for me to debug your data - there are no gene tags of any kind, so you might want to at least grep for GE:Z or gn:Z to find reads that are tagged.  For me to test, I’d need a few reads AND the header of the BAM.

-Jim

**Comment by jolespin** [comment]
I currently have the v1.13 code.  It doesn't have `TagReadWithGeneFunction` so maybe I am running an older version?

**Comment by jamesnemesh** [comment]
I would move to the 2.0 release.

-Jim

**Comment by jolespin** [comment]
Tomorrow I will recreate the pipeline using the 2.0 release.  I'm currently using a protocol generated from version `1.12` release with this [pipeline](https://github.com/mccrowjp/Dropseq).

Are there any key differences between `1.12` and `2.0` besides replacing the `TagReadWithGeneExon ` step with `TagReadWithGeneFunction` I should be keep in mind?  I will read the full protocol but just in case something comes to mind off the top of your head.

**Comment by alecw** [comment]
Please submit a new issue when you have a new question.
