### ISSUE TITLE
Sequence dictionary validation across multiple sources

### ISSUE THREAD

**Issue by jamesnemesh** [broadinstitute/Drop-seq#39]
We need a general purpose tool to do sequence dictionary validation across multiple sources.  This tool should produce the set of contigs that intersect the two sequence dictionaries.  Possible inputs should be:

IntervalList
BAM
VCF

**Comment by alecw** [comment]
Hi @jamesnemesh ,

A few questions:

* This is a function or method, not a CLP, right?
* Does the function take 2 Files, and determine file type via extension?  Or does it take SamReader, IntervalList or VCFFileReader objects?
* What is the definition of sequence equality between two sources?  Just sequence name, or more fields of SAMSequenceRecord?
* Is return value a collection of strings that are the names of the sequences in common?

Thanks, Alec

**Comment by jamesnemesh** [comment]
Hi.  It’s a function/method/helper class to encapsulate this validation, as we’ll then use it in a large number of programs (all of dropseq/census-seq specific code).

It should take SamReader, IntervalList, VCFFileReader (objects already instantiated that have SD’s.  OR, it could just take a pair of sequence dictionaries (I guess those are easy enough to pull from those classes.)

The goal is to find the list of sequences that overlap between the two (especially if they don’t overlap at all.). Returning the list of contig names that overlap the two inputs should be sufficient.  I was thinking that since we’ll do the same error reporting whenever that length is 0, it might be worth abstracting that and writing it once…and that output might be semi-verbose.

Actually, I think you do something really similar when you validate a GTF file and a reference sequence…maybe we just make that generic and encapsulate the error reporting so it’s reusable for all the object types?

messages.sequencesOnlyInReference.addAll(subtract(sequencesInReference, sequencesInGtf));
messages.sequencesOnlyInGtf.addAll(gtfReader.getUnrecognizedSequences());

messages.fractionOfSequencesOnlyInReference = messages.sequencesOnlyInReference.size()/(double)sequencesInReference.size();
long sizeOfOnlyInReference = 0;
for (final String s : messages.sequencesOnlyInReference) {
      sizeOfOnlyInReference += sequenceDictionary.getSequence(s).getSequenceLength();
}
messages.fractionOfGenomeOfSequencesOnlyInReference = sizeOfOnlyInReference/(double)sequenceDictionary.getReferenceLength();
messages.fractionOfSequencesOnlyInGtf = messages.sequencesOnlyInGtf.size()/(double)sequencesInGtf.size();

-Jim

**Comment by jamesnemesh** [comment]
Lemme amend one more thing.

The thing I’d report would be the number and names of the sequences that overlap for my programs, unless the count was 0, in which case I’d report the sequences private to each of the sources.

Contigs in common: chr1, chr2, chr3

OR:

No contigs in common!

VCF contigs 1,2,3
BAM contigs chr1, chr2, chr3

(Program exits)

-Jim

**Comment by alecw** [comment]
How does this look? https://github.com/broadinstitute/Drop-seq/pull/109

**Comment by alecw** [comment]
Resolved
