### ISSUE TITLE
genes.intervel

### ISSUE THREAD

**Issue by penglbio** [broadinstitute/Drop-seq#63]

**Comment by penglbio** [comment]
how I can get the genes.intervel formats file from the gtf

**Comment by alecw** [comment]
Hi @penglbio ,

Look at the "MetaData Creation Programs" section in https://github.com/broadinstitute/Drop-seq/blob/master/doc/Drop-seq_Alignment_Cookbook.pdf, in particular CreateIntervalsFiles.

-Alec
