### ISSUE TITLE
Is these java tools need to install

### ISSUE THREAD

**Issue by wangmhan** [broadinstitute/Drop-seq#72]
Hi, 

Don't find any description about how to install these java files in cookbook. Always got "command not found" error when run, for example: TagBamWithReadSequenceExtended or others as well.
Not familiar with Java, and cannot use java -jar to handle these .java files. Also tried javac, but end up with many errors.
Could anyone tell how to make these files executable? Many thanks!

**Comment by alecw** [comment]
Did you download the [release bundle](https://github.com/broadinstitute/Drop-seq/releases/download/v2.0.0/Drop-seq_tools-2.0.0.zip)?  There is no need to download source code (i.e. .java files).  All you need to do is unpack the zip file.  The scripts are all executable.

**Comment by wangmhan** [comment]
Thank you, that solve my problem!

alecw <notifications@github.com> 于2019年1月14日周一 下午3:23写道：
