### ISSUE TITLE
Error: DigitalExpression

### ISSUE THREAD

**Issue by wangmhan** [broadinstitute/Drop-seq#73]
Hi,

Meet error when run DigitalExpression. Both failed to the same error, when try to use the pipeline final.bam, or gene_tagged.bam.
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException

How to fix it?
Many thanks!

**Comment by jamesnemesh** [comment]
You might paste the entire error message in to help us understand what’s going on.

NoSuchFileException for the most part means it can’t find one of the input files, or you’re directing output to a directory that doesn’t exist.

-Jim

**Comment by wangmhan** [comment]
Hi,
my command:
/mnt/hel/home/menwan/software/drop_seq/DigitalExpression \
  I=S6WT_2_final.bam O=S6WT_2_final.dge.txt.gz \
  SUMMARY=S6WT_2_gene_final.dge.summary.txt \
  NUM_CORE_BARCODES=100

I got a dge.txt with only barcode header, but no gene count at all.

the entire log is:
INFO    2019-01-15 16:10:12     DigitalExpression

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    DigitalExpression -I S6WT_2_final.bam -O S6WT_2_final.dge.txt.gz -SUMMARY S6WT_2_gene_final.dge.summary.txt -NUM_CORE_BARCODES 100
**********


16:10:12.971 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop_seq/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
16:10:12.980 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
16:10:12.981 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop_seq/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
16:10:12.981 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Tue Jan 15 16:10:12 CET 2019] DigitalExpression SUMMARY=S6WT_2_gene_final.dge.summary.txt OUTPUT=S6WT_2_final.dge.txt.gz INPUT=S6WT_2_final.bam NUM_CORE_BARCODES=100    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf STRAND_STRATEGY=SENSE LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Jan 15 16:10:12 CET 2019] Executing as menwan@loki on Linux 4.4.0-127-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.0.0(1ef3a59_1539205128)
16:10:12.999 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2019-01-15 16:10:50     BamTagHistogram Processed    10,000,000 records.  Elapsed time: 00:00:37s.  Time for last 10,000,000:   37s.  Last read position: */*
INFO    2019-01-15 16:11:19     BamTagHistogram Processed    20,000,000 records.  Elapsed time: 00:01:06s.  Time for last 10,000,000:   29s.  Last read position: */*
INFO    2019-01-15 16:11:48     BamTagHistogram Processed    30,000,000 records.  Elapsed time: 00:01:35s.  Time for last 10,000,000:   29s.  Last read position: */*
INFO    2019-01-15 16:12:09     BarcodeListRetrieval    Looking for the top 100 cell barcodes
INFO    2019-01-15 16:12:09     BarcodeListRetrieval    Selected 100 core barcodes
INFO    2019-01-15 16:12:09     DigitalExpression       Calculating digital expression for [100] cells.
16:12:09.456 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
[Tue Jan 15 16:12:18 CET 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 2.10 minutes.
Runtime.totalMemory()=2505048064
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: /broad/hptmp/menwan/sortingcollection.8726913867339603115.tmp
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:268)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)
        at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:67)
        at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
        at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:133)
        at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:70)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.digitalExpression(DigitalExpression.java:188)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:154)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /broad/hptmp/menwan/sortingcollection.8726913867339603115.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
        at java.nio.file.Files.createTempFile(Files.java:852)
        at htsjdk.samtools.util.IOUtil.newTempPath(IOUtil.java:328)
        at htsjdk.samtools.util.SortingCollection.newTempFile(SortingCollection.java:279)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:250)
        ... 10 more

**Comment by alecw** [comment]
Hi,

We fixed this bug a while back but hadn't created a new release.  I just did so.  Please download [release 2.1.0](https://github.com/broadinstitute/Drop-seq/releases/tag/v2.1.0) and try again.  Let us know how it goes.

-Alec

**Comment by wangmhan** [comment]
Hi,

I just tried, but seems not change the result. the bam files generated by release 2.0.0, don't know if it matter.

The log file is:
/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/DigitalExpression \
>   I=S6WT_2_gene_tagged.bam O=S6WT_2_gene_tagged.dge.txt.gz \
>   SUMMARY=S6WT_2_gene_exon_tagged.dge.summary.txt \
>   NUM_CORE_BARCODES=100
INFO    2019-01-15 17:26:50     DigitalExpression

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    DigitalExpression -I S6WT_2_gene_tagged.bam -O S6WT_2_gene_tagged.dge.txt.gz -SUMMARY S6WT_2_gene_exon_tagged.dge.summary.txt -NUM_CORE_BARCODES 100
**********


17:26:50.338 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
17:26:50.347 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
17:26:50.348 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
17:26:50.349 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Tue Jan 15 17:26:50 CET 2019] DigitalExpression SUMMARY=S6WT_2_gene_exon_tagged.dge.summary.txt OUTPUT=S6WT_2_gene_tagged.dge.txt.gz INPUT=S6WT_2_gene_tagged.bam NUM_CORE_BARCODES=100    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf STRAND_STRATEGY=SENSE LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Jan 15 17:26:50 CET 2019] Executing as menwan@loki on Linux 4.4.0-127-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.1.0(e9a342e_1547567906)
17:26:50.432 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2019-01-15 17:27:29     BamTagHistogram Processed    10,000,000 records.  Elapsed time: 00:00:39s.  Time for last 10,000,000:   39s.  Last read position: */*
INFO    2019-01-15 17:27:59     BamTagHistogram Processed    20,000,000 records.  Elapsed time: 00:01:08s.  Time for last 10,000,000:   29s.  Last read position: */*
INFO    2019-01-15 17:28:27     BamTagHistogram Processed    30,000,000 records.  Elapsed time: 00:01:37s.  Time for last 10,000,000:   28s.  Last read position: */*
INFO    2019-01-15 17:28:51     BarcodeListRetrieval    Looking for the top 100 cell barcodes
INFO    2019-01-15 17:28:52     BarcodeListRetrieval    Selected 100 core barcodes
INFO    2019-01-15 17:28:52     DigitalExpression       Calculating digital expression for [100] cells.
17:28:52.264 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2019-01-15 17:30:34     UMIIterator     Sorting finished.
[Tue Jan 15 17:30:34 CET 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 3.73 minutes.
Runtime.totalMemory()=1512570880

**Comment by jamesnemesh** [comment]
Could you check and see if your BAM file aligned with STAR properly?  One way to look would be to count the number of HQ aligned reads in your BAM.

samtools view -q 10 S6WT_2_gene_tagged.bam |wc -l 

The program didn’t exit with any errors, which is a large change from the previous log file.

-Jim

**Comment by alecw** [comment]
The fact that the BAM file was produced by v2.0.0 should not be problem.  

Are you sure that the program did not succeed?  The output you just sent looks successful to me.  Do these files not exist?  Or do they not look correct?

* S6WT_2_gene_tagged.dge.txt.gz 
* S6WT_2_gene_exon_tagged.dge.summary.txt

**Comment by wangmhan** [comment]
Hi,It only contains header no gene read count. I will check the bam file larer to see if it work right. I checked the log file star generate, which looks normal.发自我的华为手机-------- 原始邮件 --------主题：Re: [broadinstitute/Drop-seq] Error: DigitalExpression (#73)发件人：alecw 收件人：broadinstitute/Drop-seq 抄送：wangmhan ,Author The fact that the BAM file was produced by v2.0.0 should not be problem.
Are you sure that the program did not succeed?  The output you just sent looks successful to me.  Do these files not exist?  Or do they not look correct?
S6WT_2_gene_tagged.dge.txt.gzS6WT_2_gene_exon_tagged.dge.summary.txt

**Comment by wangmhan** [comment]
Hi,

checked the bam files with "samtools view -q 10 S6WT_2_gene_tagged.bam |wc -l": 3369533;
run the new release with command: "/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/DigitalExpression I=S6WT_2_gene_tagged.bam O=S6WT_2_gene_tagged.dge.txt.gz SUMMARY=S6WT_2_gene_tagged.dge.summary.txt NUM_CORE_BARCODES=100", although did not report error, but only get the header of barcode in S6WT_2_gene_tagged.dge.txt.gz. And the S6WT_2_gene_tagged.dge.summary.txt with value 0 for each:
## METRICS CLASS        org.broadinstitute.dropseqrna.barnyard.DigitalExpression$DESummary
CELL_BARCODE    NUM_GENIC_READS NUM_TRANSCRIPTS NUM_GENES
TAGCCGGCAGTATAAG        0       0       0
AGGCCGTAGAGACTAG        0       0       0
GACTGCGAGAGACTTA        0       0       0
TCTTCGGAGGCTCATT        0       0       0

**Comment by wangmhan** [comment]
Hi again,

I remember one important thing, is that my reads is a bit difference from the normal ones.
That the barcode and UMI are in R2 not R1.
So I change some commands in the Drop-seq_alignment.sh:
# cellular tag
$echo_prefix ${dropseq_root}/TagBamWithReadSequenceExtended SUMMARY=${outdir}/unaligned_tagged_Cellular.bam_summary.txt \
  **BASE_RANGE=1-16** BASE_QUALITY=10 **BARCODED_READ=2** DISCARD_READ=false TAG_NAME=XC NUM_BASES_BELOW_QUALITY=1 \
  INPUT=${unmapped_bam} OUTPUT=$tmpdir/unaligned_tagged_Cell.bam
files_to_delete=$"files_to_delete $tmpdir/unaligned_tagged_Cell.bam"

# molecular tag
$echo_prefix ${dropseq_root}/TagBamWithReadSequenceExtended SUMMARY=${outdir}/unaligned_tagged_Molecular.bam_summary.txt \
  **BASE_RANGE=17-25** BASE_QUALITY=10 **BARCODED_READ=2** DISCARD_READ=true TAG_NAME=XM NUM_BASES_BELOW_QUALITY=1 \
  INPUT=$tmpdir/unaligned_tagged_Cell.bam OUTPUT=$tmpdir/unaligned_tagged_CellMolecular.bam
files_to_delete=$"files_to_delete $tmpdir/unaligned_tagged_CellMolecular.bam"

But actually I don't find other options, such as to align READ1 not READ2, could it be then aligned the wrong read? Or it should be fine?

Thank you for patience :)

**Comment by alecw** [comment]
It should be fine.  The second invocation of TagBamWithReadSequenceExtended, because DISCARD_READ=true, produces a non-paired BAM.  I.e. there is no longer a read1 and read2.  Just a single read with tags.

**Comment by wangmhan** [comment]
Yes, I double checked the unaligned_mc_tagged_polyA_filtered.fastq, it is the correct one: R1.
But, still cannot get right output with DigitalExpression, which is a real problem.

**Comment by alecw** [comment]
Did you re-align your fastq?  Assuming you have, could you again check the alignment result as James asked earlier:

> Could you check and see if your BAM file aligned with STAR properly?  One way to look would be to count the number of HQ aligned reads in your BAM.
>
> samtools view -q 10 S6WT_2_gene_tagged.bam |wc -l

Assuming your aligned BAM now contains some alignments, send again your DigitalExpression command line, and the console output.

**Comment by wangmhan** [comment]
Hi,
samtools view -q 10 S6WT_2_gene_tagged.bam |wc -l: 3369533

I thought final.bam would be better, so tried final.bam this time.
samtools view -q 10 S6WT_2_final.bam |wc -l :3223267

command is like this: /mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/DigitalExpression I=S6WT_2_final.bam O=S6WT_2_final.dge.txt.gz SUMMARY=S6WT_2_final.dge.summary.txt NUM_CORE_BARCODES=100

INFO    2019-01-16 15:44:28     DigitalExpression

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    DigitalExpression -I S6WT_2_final.bam -O S6WT_2_final.dge.txt.gz -SUMMARY S6WT_2_final.dge.summary.txt -NUM_CORE_BARCODES 100
**********


15:44:29.005 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
15:44:29.013 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
15:44:29.014 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/hel/home/menwan/software/drop-seq_tools-2.1.0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
15:44:29.014 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (No such file or directory)
[Wed Jan 16 15:44:29 CET 2019] DigitalExpression SUMMARY=S6WT_2_final.dge.summary.txt OUTPUT=S6WT_2_final.dge.txt.gz INPUT=S6WT_2_final.bam NUM_CORE_BARCODES=100    OUTPUT_READS_INSTEAD=false CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM EDIT_DISTANCE=1 READ_MQ=10 MIN_BC_READ_THRESHOLD=0 USE_STRAND_INFO=true RARE_UMI_FILTER_THRESHOLD=0.0 GENE_NAME_TAG=gn GENE_STRAND_TAG=gs GENE_FUNCTION_TAG=gf STRAND_STRATEGY=SENSE LOCUS_FUNCTION_LIST=[CODING, UTR] VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Jan 16 15:44:29 CET 2019] Executing as menwan@loki on Linux 4.4.0-127-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12; Deflater: Jdk; Inflater: Jdk; Provider GCS is not available; Picard version: 2.1.0(e9a342e_1547567906)
15:44:29.031 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
INFO    2019-01-16 15:45:03     BamTagHistogram Processed    10,000,000 records.  Elapsed time: 00:00:34s.  Time for last 10,000,000:   34s.  Last read position: */*
INFO    2019-01-16 15:45:29     BamTagHistogram Processed    20,000,000 records.  Elapsed time: 00:01:00s.  Time for last 10,000,000:   25s.  Last read position: */*
INFO    2019-01-16 15:45:54     BamTagHistogram Processed    30,000,000 records.  Elapsed time: 00:01:25s.  Time for last 10,000,000:   25s.  Last read position: */*
INFO    2019-01-16 15:46:13     BarcodeListRetrieval    Looking for the top 100 cell barcodes
INFO    2019-01-16 15:46:13     BarcodeListRetrieval    Selected 100 core barcodes
INFO    2019-01-16 15:46:13     DigitalExpression       Calculating digital expression for [100] cells.
15:46:13.484 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
[Wed Jan 16 15:46:21 CET 2019] org.broadinstitute.dropseqrna.barnyard.DigitalExpression done. Elapsed time: 1.87 minutes.
Runtime.totalMemory()=2508718080
Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.nio.file.NoSuchFileException: /menwan/sortingcollection.1251581774098271328.tmp
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:268)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:183)
        at org.broadinstitute.dropseqrna.utils.SortingIteratorFactory.create(SortingIteratorFactory.java:67)
        at org.broadinstitute.dropseqrna.utils.readiterators.SamRecordSortingIteratorFactory.create(SamRecordSortingIteratorFactory.java:57)
        at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:133)
        at org.broadinstitute.dropseqrna.utils.readiterators.UMIIterator.<init>(UMIIterator.java:70)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.digitalExpression(DigitalExpression.java:188)
        at org.broadinstitute.dropseqrna.barnyard.DigitalExpression.doWork(DigitalExpression.java:154)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
Caused by: java.nio.file.NoSuchFileException: /menwan/sortingcollection.1251581774098271328.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
        at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
        at java.nio.file.Files.createTempFile(Files.java:852)
        at htsjdk.samtools.util.IOUtil.newTempPath(IOUtil.java:328)
        at htsjdk.samtools.util.SortingCollection.newTempFile(SortingCollection.java:279)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:250)
        ... 10 more

**Comment by alecw** [comment]
You need to supply a temp directory that exists, either via the TMPDIR environment variable, or TMP_DIR command-line option.  Presumably the directory /menwan does not exist.

**Comment by jamesnemesh** [comment]
Since your samtools view indicates there are aligned reads, let’s see if they are properly tagged.

Please send us the results of the following:
samtools view -q 10 S6WT_2_final.bam |grep gn:Z |head -n 5

If this produces no results, we have an answer.  Otherwise, it’ll be worth checking that your reads appear to have correct tags.  

If this is uninformative, you might consider uploading your BAM to some file sharing service (dropbox, etc) and sharing a link with us so I can grab a copy of it and run DGE myself to understand what’s going on.

-Jim

**Comment by wangmhan** [comment]
Hi,

alecw is correct! Need to add TMP_DIR=tmp, and finally got an output looks reasonable!
Actually, I tried to add TMP_DIR=tmp when use version 2.0.0, but failed.
And this time, it worked :)

**Comment by wangmhan** [comment]
And one more question:
I checked the output, the number of genes (13500) seems not the same as the gtf files I provide (around 50000).
Is it because it only output the genes with expression >1 in total, or any other reason?

**Comment by jamesnemesh** [comment]
You will only see genes that were expressed in at least one cell.

-Jim

**Comment by wangmhan** [comment]
I see. Thank you :)
