### ISSUE TITLE
Compare mapping rate between v1.13 and v2.1

### ISSUE THREAD

**Issue by wangmhan** [broadinstitute/Drop-seq#77]
### Instructions
Use the same bam file, and getting really different mapping rate. v1.13 is much more higher than v2.1, which seems unreasonable.
- Use a **concise** yet **descriptive** title;

### Tool(s) involved
_Tool name(s), special parameters?_
Drop-seq_tools-1.13
Drop-seq_tools-2.1

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._
Using the same parameter, and same reference.
I run separately the same bam files to v1.13 and v2.1.
Checked the star.Log.final.out, the mapping rate is nearly double for v1.13, compare to v2.1.
Also checked the dge.summary.txt for each final.bam through the pipeline: Drop-seq_alignment.sh, also nearly double number of reads in v1.13.
Which seems unreasonable, as new release should be more robust and have better performance.

Have you guys compare the difference between release yourself?

**Comment by alecw** [comment]
There are almost no changes between v1.13 and 2.1 for the pre-alignment part of the pipeline with the exception of a slightly refined polyA trimmer (which is more accurate now, and should provide more mapped reads), and you’re claiming different mapping rates from STAR.  Are you using the same version of STAR for both alignments, and same reference?

I suggest you run both 1.13 and 2.1 pipelines, and compare the intermediate files.  For 2.1, use -k option to keep intermediate files.  For 1.13, edit the script and comment out the last line, which removes intermediate files.  Also, do not use -p option.  

Then you can compare the intermediate files.  Given that you are reporting enormously different mapping rates from STAR, you don't need to look at anything that runs after STAR.  What I expect is that the output of each invocation of TagBamWithReadSequenceExtended should be identical between the 2 versions, likewise the output of FilterBam and TrimStartingSequence.  For PolyATrimmer, there should be a small number of differences.  The total number of alignment differences should be <= the number of PolyATrimmer differences, unless you're running your aligner differently.

**Comment by wangmhan** [comment]
Yes, I am using the same version of STAR for both alignments, with same reference.
