### ISSUE TITLE
NullPointerException in DetectBeadSubstitutionErrors

### ISSUE THREAD

**Issue by kpj** [broadinstitute/Drop-seq#90]
Hello,

I am using Drop-seq tools 2.1.0 (on Mac OS X 10.14.3 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01), and I experience a `NullPointerException` when running `DetectBeadSubstitutionErrors` with a sample dataset.

I have a small BAM file (that I obtain after the BAM-merging step of the Drop-seq cookbook) with the following content:
```
@SQ	SN:reference	LN:480	M5:e2bab1c08a80791697103dce6a53b637	UR:file:/data/reference.fasta
read1	0	reference	1	255	64M	*	0	0	TATCGATTTATCTGACCAGATGGCTAGCTATTTTACGCCTTTACGCAGAACTATTCGCTGGTAC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	XC:Z:AGTTANGGGGGA	MD:Z:64	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:0	XM:Z:CAGGTTGT	UQ:i:0	XQ:i:1	AS:i:62
read2	0	reference	1	255	64M	*	0	0	TATCGATTTATCTGACCAGATGGCTAGCTATTTTACGCCTTTACGCAGAACTATTCGCTGGTAC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	XC:Z:AGTTANGGGGGA	MD:Z:64	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:0	XM:Z:CAGGTTGT	UQ:i:0	XQ:i:1	AS:i:62
read3	0	reference	1	255	64M	*	0	0	TATCGATTTATCTGACCAGATGGCTAGCTATTTTACGCCTTTACGCAGAACTATTCGCTGGTAC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	XC:Z:AAAAAAAAAAAA	MD:Z:64	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:0	XM:Z:ATTTTTTT	UQ:i:0	AS:i:62
read4	0	reference	1	255	64M	*	0	0	CATTTCTAATGCTGGAGATGAATAAAGATCAACGGCGTAGAATTCGCGCATCTCTTTTGTGCAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	XC:Z:CCCGACGGTAGT	MD:Z:3A60	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:1	XM:Z:CCATCTGC	UQ:i:40	AS:i:60
read5	0	reference	1	255	64M	*	0	0	CATATCTAATGCTGGAGATGAATAAAGATCAACGGCGTAGAATTCGCGCATCTCTTTTGTGCAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	XC:Z:CCCGACGGTAGT	MD:Z:64	PG:Z:STAR	RG:Z:A	NH:i:1	NM:i:0	XM:Z:CCATCTGC	UQ:i:0	AS:i:62
```
Each read is tagged with the cellular barcode (XC) and UMI (XM).

If I now try to correct substitution errors, I get a `NullPointerException`:
```bash
$ DetectBeadSubstitutionErrors I=aligned_merged.bam O=aligned_merged_corrected.bam
INFO	2019-02-15 11:31:46	DetectBeadSubstitutionErrors
11:31:47.115 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Fri Feb 15 11:31:47 CET 2019] DetectBeadSubstitutionErrors INPUT=[aligned_merged.bam] OUTPUT=aligned_merged_corrected.bam    FILTER_AMBIGUOUS=true FREQ_COMMON_SUBSTITUTION=0.8 CELL_BARCODE_TAG=XC MOLECULAR_BARCODE_TAG=XM GENE_EXON_TAG=GE STRAND_TAG=GS MIN_UMIS_PER_CELL=20 UMI_BIAS_THRESHOLD=0.8 EDIT_DISTANCE=1 READ_MQ=10 NUM_THREADS=1 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Feb 15 11:31:47 CET 2019] Executing as kpj on Mac OS X 10.14.3 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_144-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.1.0(e9a342e_1547567906)
INFO	2019-02-15 11:31:47	UMIIterator	Sorting finished.
INFO	2019-02-15 11:31:47	DetectBeadSubstitutionErrors	Gathering UMI counts per cell and filtering out UMI biased barcodes as appropriate
INFO	2019-02-15 11:31:47	DetectBeadSubstitutionErrors	Finished gathering a list of cell barcodes to collapse
INFO	2019-02-15 11:31:47	DetectBeadSubstitutionErrors	Discovered [0] barcodes that were excluded due to incomplete synthesis and had T bias at last base of UMI [null]
[Fri Feb 15 11:31:47 CET 2019] org.broadinstitute.dropseqrna.utils.editdistance.DetectBeadSubstitutionErrors done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=257425408
Exception in thread "main" java.lang.NullPointerException
	at org.broadinstitute.dropseqrna.utils.editdistance.DetectBeadSubstitutionErrors.getUMIsPerCell(DetectBeadSubstitutionErrors.java:395)
	at org.broadinstitute.dropseqrna.utils.editdistance.DetectBeadSubstitutionErrors.doWork(DetectBeadSubstitutionErrors.java:154)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at org.broadinstitute.dropseqrna.cmdline.DropSeqMain.main(DropSeqMain.java:42)
```

I tried to play with `MIN_UMIS_PER_CELL` and similar options, but always arrived at the same exception. Could this be related to other missing tags or that fact that no incorrect barcodes were found?
Although I should probably not end up with a NullPointerException in any case.

I took a quick look at `DetectBeadSubstitutionErrors.java:395`, and it seems like `polyTPosition` being `null` is the problem. But I don't understand the code enough to make a reasonable judgement.
Does anyone have an idea what could be going wrong here?

**Comment by jamesnemesh** [comment]
I *think* what’s going on is the following:

You don’t have functional annotations tagged on to your data (you missed a step), and you need to run TagReadWithGeneFunction first to get gn,gs,gf tags that are used to interpret what the UMIs are in your data.  Because these are missing, there are no reads found to evaluate where the last base of the UMI is (so it goes unset).

You’re absolutely right and this should never not null pointer in any situation, so we’ll work on cleaning up that up.

-Jim

**Comment by kpj** [comment]
Thank you for your response. I have indeed not used TagReadWithGeneFunction, because I (at the moment) do not require the information it adds.
Is there a way of correcting bead errors without gene annotations?

I tried to manually add the required tags (`GN:Z:foo	GS:Z:foo	GF:Z:foo`) to each read, but it still resulted in a NullPointerException.
Would it be a better idea to run TagReadWithGeneFunction with an empty GTF file?

**Comment by jamesnemesh** [comment]
You need real values for those tags for DetectBeadSubstitutionErrors to run correctly.  Invalid tag values aren’t going to cut it. I suggest you follow the cookbook and appropriately prepare your data if you wish to use our code - the pre-processing steps are there for a reason.  

In this case, we use UMIs to detect when molecular barcodes are generated incorrectly.  Without valid gene, function, and strand tags, we can’t determine what UMIs we have, so we can’t detect problems.

I suggest you look at the cookbook if you want further info on how this works.

-Jim
